#!/usr/bin/env python3
"""
Build complete IPC 1-511 → BNS cross-reference.
Loads the existing ipc_bns_mapping.json, adds ipc_complete_mapping array,
and writes back to the same file.  All entries: verified = false.
"""
import json
from pathlib import Path

FILE = Path("/app/backend/ipc_bns_mapping.json")

# ─────────────────────────────────────────────────────────────────────────────
# MASTER MAPPING
# Each tuple: (ipc_section, bns_section_or_None, offence_title, change_type, note)
# change_type: renumbering_only | substantive_change | deleted | merged
# bns_section = None  ⟹  deleted/no equivalent
# ─────────────────────────────────────────────────────────────────────────────
ENTRIES = [
    # ── CHAPTER I  PRELIMINARY (IPC 1-5) ──────────────────────────────────────
    ("1",   "1",     "Short title",
     "substantive_change",
     "Renamed from 'Indian Penal Code 1860' to 'Bharatiya Nyaya Sanhita 2023'. Effective 1 July 2024."),
    ("2",   "2",     "Punishment of offences committed within India",
     "substantive_change",
     "Expanded to include offences committed through electronic/digital means from outside India."),
    ("3",   "3",     "Punishment of offences committed beyond, but triable within, India",
     "renumbering_only",
     "Section renumbered; substance unchanged."),
    ("4",   "4",     "Extension of Code to extra-territorial offences",
     "substantive_change",
     "BNS Sec 4 explicitly adds organised crime and terrorism as extra-territorial offences."),
    ("5",   "5",     "Certain laws not to be affected by this Act",
     "renumbering_only",
     "Saving clause for special and local laws; unchanged."),

    # ── CHAPTER II  GENERAL EXPLANATIONS (IPC 6-52A) ─────────────────────────
    ("6",   "6",     "Definitions in the Code to be understood subject to exceptions",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("7",   "2",     "Sense of expression once explained",
     "merged",
     "Absorbed into BNS Section 2 (general definitions chapter)."),
    ("8",   "2",     "Gender",
     "merged",
     "Definition of gender merged into BNS Section 2 definitions."),
    ("9",   "2",     "Number",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("10",  "2",     "Man, Woman",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("11",  "2",     "Person",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("12",  "2",     "Public",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("13",  "2",     "Queen / Government",
     "substantive_change",
     "Reference to 'Queen' replaced with 'Government of India'; merged into BNS Sec 2."),
    ("14",  "2",     "Servant of Government",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("15",  "2",     "British India",
     "merged",
     "Colonial reference removed; merged as 'India' into BNS Sec 2."),
    ("16",  "2",     "Government of India",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("17",  "2",     "Government",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("18",  "2",     "India",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("19",  "2",     "Judge",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("20",  "2",     "Court of Justice",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("21",  "2(17)", "Public servant",
     "substantive_change",
     "BNS Sec 2(17) retains the comprehensive definition. Clarifies that elected members of Parliament and state legislatures are included."),
    ("22",  "2",     "Moveable property",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("23",  "2",     "Wrongful gain",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("24",  "2",     "Dishonestly",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("25",  "2",     "Fraudulently",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("26",  "2",     "Reason to believe",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("27",  "2",     "Property in possession of wife, clerk, or servant",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("28",  "2",     "Counterfeit",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("29",  "2",     "Document",
     "substantive_change",
     "BNS Sec 2 definition of 'document' explicitly includes electronic records and digital documents."),
    ("30",  "2",     "Valuable security",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("31",  "2",     "A will",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("32",  "2",     "Words referring to acts include illegal omissions",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("33",  "2",     "Act, omission",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("34",  "3(5)",  "Acts done by several persons in furtherance of common intention",
     "renumbering_only",
     "Common intention principle renumbered to BNS 3(5). Substance unchanged — joint liability for acts in furtherance of common intention."),
    ("35",  "3",     "When such an act is criminal by reason of its being done with a criminal knowledge or intention",
     "merged",
     "Merged into BNS Section 3 general explanations."),
    ("36",  "3",     "Effect caused partly by act and partly by omission",
     "merged",
     "Merged into BNS Section 3."),
    ("37",  "3",     "Co-operation by doing one of several acts constituting an offence",
     "merged",
     "Merged into BNS Section 3."),
    ("38",  "3",     "Persons concerned in criminal act may be guilty of different offences",
     "merged",
     "Merged into BNS Section 3."),
    ("39",  "2",     "Voluntarily",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("40",  "2",     "Offence",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("41",  "2",     "Special law",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("42",  "2",     "Local law",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("43",  "2",     "Illegal, legally bound to do",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("44",  "2",     "Injury",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("45",  "2",     "Life",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("46",  "2",     "Death",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("47",  "2",     "Animal",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("48",  "2",     "Vessel",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("49",  "2",     "Year, Month",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("50",  "2",     "Section",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("51",  "2",     "Oath",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("52",  "2",     "Good faith",
     "merged",
     "Merged into BNS Section 2 definitions."),
    ("52A", "2",     "Harbour",
     "merged",
     "Definition of harbour merged into BNS Section 2 definitions."),

    # ── CHAPTER III  PUNISHMENTS (IPC 53-75) ──────────────────────────────────
    ("53",  "4",     "Punishments",
     "substantive_change",
     "BNS Sec 4 adds 'community service' as a new form of punishment. Transportation removed (was already obsolete). Forfeiture of property retained."),
    ("54",  "5",     "Commutation of sentence of death",
     "renumbering_only",
     "Renumbered to BNS 5; substance unchanged."),
    ("55",  "6",     "Commutation of sentence of imprisonment for life",
     "renumbering_only",
     "Renumbered to BNS 6; substance unchanged."),
    ("55A", "7",     "Definition of 'imprisonment for life'",
     "renumbering_only",
     "Renumbered to BNS 7; substance unchanged — imprisonment for life means imprisonment for the remainder of natural life."),
    ("56",  None,    "Sentence of Europeans and Americans to transportation",
     "deleted",
     "Deleted. This was a colonial-era provision applicable only to European and American offenders. Transportation as a punishment has been abolished."),
    ("57",  "8",     "Fractions of terms of punishment",
     "renumbering_only",
     "Renumbered to BNS 8; substance unchanged."),
    ("58",  None,    "Offenders sentenced to transportation how dealt with until transported",
     "deleted",
     "Deleted. Transportation as a punishment has been abolished."),
    ("59",  None,    "Transportation instead of imprisonment",
     "deleted",
     "Deleted. Transportation as a punishment has been abolished."),
    ("60",  "9",     "Sentence may be (in certain cases of imprisonment) wholly or partly rigorous or simple",
     "renumbering_only",
     "Renumbered to BNS 9; substance unchanged."),
    ("61",  None,    "Sentence of forfeiture of property",
     "deleted",
     "Deleted as a standalone section; forfeiture of property is now incorporated directly into BNS Sec 4 (Punishments)."),
    ("62",  None,    "Forfeiture of property in respect of offenders punishable with death or transportation",
     "deleted",
     "Deleted. Merged into the punishments framework under BNS Sec 4."),
    ("63",  "10",    "Amount of fine",
     "renumbering_only",
     "Renumbered to BNS 10; substance unchanged."),
    ("64",  "11",    "Sentence of imprisonment for non-payment of fine",
     "renumbering_only",
     "Renumbered to BNS 11; substance unchanged."),
    ("65",  "12",    "Limit to imprisonment for non-payment of fine, when imprisonment and fine awardable",
     "renumbering_only",
     "Renumbered to BNS 12; substance unchanged."),
    ("66",  "13",    "Description of imprisonment for non-payment of fine",
     "renumbering_only",
     "Renumbered to BNS 13; substance unchanged."),
    ("67",  "14",    "Imprisonment for non-payment of fine when offender has been previously imprisoned",
     "renumbering_only",
     "Renumbered to BNS 14; substance unchanged."),
    ("68",  "15",    "Fine leviable within six years, or during imprisonment",
     "renumbering_only",
     "Renumbered to BNS 15; substance unchanged."),
    ("69",  "16",    "Termination of imprisonment on payment of fine",
     "renumbering_only",
     "Renumbered to BNS 16; substance unchanged."),
    ("70",  "17",    "Fine not leviable by reason of death of offender",
     "renumbering_only",
     "Renumbered to BNS 17; substance unchanged."),
    ("71",  "18",    "Limit of punishment of offence made up of several offences",
     "renumbering_only",
     "Renumbered to BNS 18; substance unchanged."),
    ("72",  "19",    "Punishment of person guilty of one of several offences, judgment stating that it is doubtful of which",
     "renumbering_only",
     "Renumbered to BNS 19; substance unchanged."),
    ("73",  "20",    "Solitary confinement",
     "renumbering_only",
     "Renumbered to BNS 20; substance unchanged."),
    ("74",  "21",    "Limit of solitary confinement",
     "renumbering_only",
     "Renumbered to BNS 21; substance unchanged."),
    ("75",  "22",    "Enhanced punishment for certain offences under Chapter XII or XVII after previous conviction",
     "renumbering_only",
     "Renumbered to BNS 22; substance unchanged."),

    # ── CHAPTER IV  GENERAL EXCEPTIONS (IPC 76-106) ───────────────────────────
    ("76",  "23",    "Act done by a person bound, or by mistake of fact believing himself, bound by law",
     "renumbering_only",
     "Renumbered to BNS 23; substance unchanged."),
    ("77",  "24",    "Act of a Judge when acting judicially",
     "renumbering_only",
     "Renumbered to BNS 24; substance unchanged."),
    ("78",  "25",    "Act done pursuant to the judgment or order of Court",
     "renumbering_only",
     "Renumbered to BNS 25; substance unchanged."),
    ("79",  "26",    "Act done by a person justified, or by mistake of fact believing himself, justified, by law",
     "renumbering_only",
     "Renumbered to BNS 26; substance unchanged."),
    ("80",  "27",    "Accident in doing a lawful act",
     "renumbering_only",
     "Renumbered to BNS 27; substance unchanged."),
    ("81",  "28",    "Act likely to cause harm, but done without criminal intent, and to prevent other harm",
     "renumbering_only",
     "Renumbered to BNS 28; substance unchanged."),
    ("82",  "29",    "Act of a child under seven years of age",
     "renumbering_only",
     "Renumbered to BNS 29; substance unchanged."),
    ("83",  "30",    "Act of a child above seven and under twelve of immature understanding",
     "renumbering_only",
     "Renumbered to BNS 30; substance unchanged."),
    ("84",  "31",    "Act of a person of unsound mind",
     "renumbering_only",
     "Renumbered to BNS 31; substance unchanged."),
    ("85",  "32",    "Act of a person incapable of judgment by reason of intoxication caused against his will",
     "renumbering_only",
     "Renumbered to BNS 32; substance unchanged."),
    ("86",  "33",    "Offence requiring a particular intent or knowledge committed by one who is intoxicated",
     "renumbering_only",
     "Renumbered to BNS 33; substance unchanged."),
    ("87",  "34",    "Act not intended and not known to be likely to cause death or grievous hurt, done by consent",
     "renumbering_only",
     "Renumbered to BNS 34; substance unchanged."),
    ("88",  "35",    "Act not intended to cause death, done by consent in good faith for person's benefit",
     "renumbering_only",
     "Renumbered to BNS 35; substance unchanged."),
    ("89",  "36",    "Act done in good faith for benefit of child or insane person, by or by consent of guardian",
     "renumbering_only",
     "Renumbered to BNS 36; substance unchanged."),
    ("90",  "37",    "Consent known to be given under fear or misconception",
     "renumbering_only",
     "Renumbered to BNS 37; substance unchanged."),
    ("91",  "38",    "Exclusion of acts which are offences independently of harm caused",
     "renumbering_only",
     "Renumbered to BNS 38; substance unchanged."),
    ("92",  "39",    "Act done in good faith for benefit of a person without consent",
     "renumbering_only",
     "Renumbered to BNS 39; substance unchanged."),
    ("93",  "40",    "Communication made in good faith",
     "renumbering_only",
     "Renumbered to BNS 40; substance unchanged."),
    ("94",  "41",    "Act to which a person is compelled by threats",
     "renumbering_only",
     "Renumbered to BNS 41; substance unchanged."),
    ("95",  "42",    "Act causing slight harm",
     "renumbering_only",
     "Renumbered to BNS 42; substance unchanged."),
    ("96",  "43",    "Things done in private defence",
     "renumbering_only",
     "Renumbered to BNS 43; substance unchanged."),
    ("97",  "44",    "Right of private defence of the body and of property",
     "renumbering_only",
     "Renumbered to BNS 44; substance unchanged."),
    ("98",  "45",    "Right of private defence against act of person of unsound mind, etc.",
     "renumbering_only",
     "Renumbered to BNS 45; substance unchanged."),
    ("99",  "46",    "Acts against which there is no right of private defence",
     "renumbering_only",
     "Renumbered to BNS 46; substance unchanged."),
    ("100", "47",    "When the right of private defence of the body extends to causing death",
     "renumbering_only",
     "Renumbered to BNS 47; substance unchanged."),
    ("101", "48",    "When such right extends to causing any harm other than death",
     "renumbering_only",
     "Renumbered to BNS 48; substance unchanged."),
    ("102", "49",    "Commencement and continuance of the right of private defence of the body",
     "renumbering_only",
     "Renumbered to BNS 49; substance unchanged."),
    ("103", "50",    "When the right of private defence of property extends to causing death",
     "renumbering_only",
     "Renumbered to BNS 50; substance unchanged."),
    ("104", "51",    "When such right extends to causing any harm other than death",
     "renumbering_only",
     "Renumbered to BNS 51; substance unchanged."),
    ("105", "52",    "Commencement and continuance of the right of private defence of property",
     "renumbering_only",
     "Renumbered to BNS 52; substance unchanged."),
    ("106", "53",    "Right of private defence against deadly assault when there is risk of harm to innocent person",
     "renumbering_only",
     "Renumbered to BNS 53; substance unchanged."),

    # ── CHAPTER V  ABETMENT (IPC 107-120) and CHAPTER VA  CONSPIRACY (120A-120B)
    ("107", "45",    "Abetment of a thing",
     "renumbering_only",
     "Renumbered to BNS 45; three modes of abetment (instigation, conspiracy, intentional aid) unchanged."),
    ("108", "46",    "Abettor",
     "renumbering_only",
     "Renumbered to BNS 46; substance unchanged."),
    ("108A","47",    "Abetment in India of offences outside India",
     "renumbering_only",
     "Renumbered to BNS 47; substance unchanged."),
    ("109", "48",    "Punishment of abetment if the act abetted is committed",
     "renumbering_only",
     "Renumbered to BNS 48; substance unchanged."),
    ("110", "49",    "Punishment of abetment if person abetted acts under different intention",
     "renumbering_only",
     "Renumbered to BNS 49; substance unchanged."),
    ("111", "50",    "Liability of abettor when one act abetted and different act done",
     "renumbering_only",
     "Renumbered to BNS 50; substance unchanged."),
    ("112", "51",    "Abettor when liable to cumulative punishment for act abetted and for act done",
     "renumbering_only",
     "Renumbered to BNS 51; substance unchanged."),
    ("113", "52",    "Liability of abettor for an effect caused by the act abetted different from that intended by the abettor",
     "renumbering_only",
     "Renumbered to BNS 52; substance unchanged."),
    ("114", "53",    "Abettor present when offence is committed",
     "renumbering_only",
     "Renumbered to BNS 53; substance unchanged."),
    ("115", "54",    "Abetment of offence punishable with death or imprisonment for life",
     "renumbering_only",
     "Renumbered to BNS 54; substance unchanged."),
    ("116", "55",    "Abetment of offence punishable with imprisonment",
     "renumbering_only",
     "Renumbered to BNS 55; substance unchanged."),
    ("117", "56",    "Abetting commission of offence by the public or by more than ten persons",
     "renumbering_only",
     "Renumbered to BNS 56; substance unchanged."),
    ("118", "57",    "Concealing design to commit offence punishable with death or imprisonment for life",
     "renumbering_only",
     "Renumbered to BNS 57; substance unchanged."),
    ("119", "58",    "Public servant concealing design to commit offence which it is his duty to prevent",
     "renumbering_only",
     "Renumbered to BNS 58; substance unchanged."),
    ("120", "59",    "Concealing design to commit offence punishable with imprisonment",
     "renumbering_only",
     "Renumbered to BNS 59; substance unchanged."),
    ("120A","60",    "Definition of criminal conspiracy",
     "renumbering_only",
     "Renumbered to BNS 60; definition (agreement of two or more persons to commit offence) unchanged."),
    ("120B","61",    "Punishment of criminal conspiracy",
     "renumbering_only",
     "Renumbered to BNS 61; punishment for criminal conspiracy unchanged."),

    # ── CHAPTER VI  OFFENCES AGAINST THE STATE (IPC 121-130) ─────────────────
    ("121", "147",   "Waging, or attempting to wage war, or abetting waging of war, against the Government of India",
     "renumbering_only",
     "Renumbered to BNS 147; punishment (death or life) unchanged."),
    ("121A","148",   "Conspiracy to commit offences punishable by section 121",
     "renumbering_only",
     "Renumbered to BNS 148; substance unchanged."),
    ("122", "149",   "Collecting arms, etc., with intention of waging war against the Government of India",
     "renumbering_only",
     "Renumbered to BNS 149; substance unchanged."),
    ("123", "150",   "Concealing with intent to facilitate design to wage war",
     "renumbering_only",
     "Renumbered to BNS 150; substance unchanged."),
    ("124", "151",   "Assaulting President, Governor, etc., with intent to compel or restrain the exercise of any lawful power",
     "renumbering_only",
     "Renumbered to BNS 151; substance unchanged."),
    ("124A","152",   "Sedition (Acts endangering sovereignty, unity and integrity of India)",
     "substantive_change",
     "IPC 124A 'sedition' replaced by BNS 152. The word 'sedition' is dropped. BNS 152 criminalises acts that excite secession, armed rebellion, subversive activities, or separatist activities against the constitutional order. Removes 'disaffection' requirement. Punishment: up to life imprisonment. Highly contested provision."),
    ("125", "153",   "Waging war against any Asiatic Power in alliance or at peace with the Government of India",
     "renumbering_only",
     "Renumbered to BNS 153; substance unchanged."),
    ("126", "154",   "Committing depredation on territories of Power at peace with the Government of India",
     "renumbering_only",
     "Renumbered to BNS 154; substance unchanged."),
    ("127", "155",   "Receiving property taken by war or depredation",
     "renumbering_only",
     "Renumbered to BNS 155; substance unchanged."),
    ("128", "156",   "Public servant voluntarily allowing prisoner of State or war to escape",
     "renumbering_only",
     "Renumbered to BNS 156; substance unchanged."),
    ("129", "157",   "Public servant negligently suffering such prisoner to escape",
     "renumbering_only",
     "Renumbered to BNS 157; substance unchanged."),
    ("130", "158",   "Aiding escape of, rescuing or harbouring such prisoner",
     "renumbering_only",
     "Renumbered to BNS 158; substance unchanged."),

    # ── CHAPTER VII  OFFENCES RELATING TO THE ARMY, NAVY AND AIR FORCE (IPC 131-140)
    ("131", "160",   "Abetting mutiny, or attempting to seduce a soldier, sailor or airman from his duty",
     "renumbering_only",
     "Renumbered to BNS 160; substance unchanged."),
    ("132", "161",   "Abetment of mutiny, if mutiny is committed in consequence thereof",
     "renumbering_only",
     "Renumbered to BNS 161; substance unchanged."),
    ("133", "162",   "Abetment of assault by soldier, sailor or airman on his superior officer, when in execution of his office",
     "renumbering_only",
     "Renumbered to BNS 162; substance unchanged."),
    ("134", "163",   "Abetment of such assault, if the assault is committed",
     "renumbering_only",
     "Renumbered to BNS 163; substance unchanged."),
    ("135", "164",   "Abetment of desertion of soldier, sailor or airman",
     "renumbering_only",
     "Renumbered to BNS 164; substance unchanged."),
    ("136", "165",   "Harbouring deserter",
     "renumbering_only",
     "Renumbered to BNS 165; substance unchanged."),
    ("137", "166",   "Deserter concealed on board merchant vessel through negligence of master",
     "renumbering_only",
     "Renumbered to BNS 166; substance unchanged."),
    ("138", "167",   "Abetment of act of insubordination by soldier, sailor or airman",
     "renumbering_only",
     "Renumbered to BNS 167; substance unchanged."),
    ("138A",None,    "Application to Indian Marine Service",
     "deleted",
     "Deleted. Reference to Indian Marine Service is obsolete."),
    ("139", "168",   "Persons subject to Articles of War, etc., not liable to punishment under this Code for certain offences",
     "renumbering_only",
     "Renumbered to BNS 168; substance unchanged."),
    ("140", "169",   "Wearing garb or carrying token used by soldier, sailor or airman",
     "renumbering_only",
     "Renumbered to BNS 169; substance unchanged."),

    # ── CHAPTER VIII  OFFENCES AGAINST PUBLIC TRANQUILITY (IPC 141-160) ──────
    ("141", "189",   "Unlawful assembly",
     "renumbering_only",
     "Renumbered to BNS 189; definition of unlawful assembly (5+ persons with common unlawful object) unchanged."),
    ("142", "190",   "Being member of unlawful assembly",
     "renumbering_only",
     "Renumbered to BNS 190; substance unchanged."),
    ("143", "191",   "Punishment",
     "renumbering_only",
     "Renumbered to BNS 191; punishment for member of unlawful assembly (up to 6 months) unchanged."),
    ("144", "191(1)","Joining unlawful assembly armed with deadly weapon",
     "renumbering_only",
     "Renumbered to BNS 191(1); substance unchanged."),
    ("145", "192",   "Joining or continuing in unlawful assembly, knowing it has been commanded to disperse",
     "renumbering_only",
     "Renumbered to BNS 192; substance unchanged."),
    ("146", "191",   "Rioting",
     "renumbering_only",
     "Renumbered to BNS 191; rioting (unlawful assembly uses force or violence) unchanged."),
    ("147", "191(2)","Punishment for rioting",
     "renumbering_only",
     "Renumbered to BNS 191(2); punishment for rioting (up to 2 years) unchanged."),
    ("148", "191(3)","Rioting, armed with deadly weapon",
     "renumbering_only",
     "Renumbered to BNS 191(3); punishment for armed rioting (up to 3 years) unchanged."),
    ("149", "190",   "Every member of unlawful assembly guilty of offence committed in prosecution of common object",
     "renumbering_only",
     "Renumbered to BNS 190; substance unchanged."),
    ("150", "193",   "Hiring, or conniving at hiring, of persons to join unlawful assembly",
     "renumbering_only",
     "Renumbered to BNS 193; substance unchanged."),
    ("151", "194",   "Knowingly joining or continuing in any assembly of five or more persons after it has been commanded to disperse",
     "renumbering_only",
     "Renumbered to BNS 194; substance unchanged."),
    ("152", "195",   "Assaulting or obstructing public servant when suppressing riot, etc.",
     "renumbering_only",
     "Renumbered to BNS 195; substance unchanged."),
    ("153", "196",   "Wantonly giving provocation with intent to cause riot — if rioting be committed",
     "renumbering_only",
     "Renumbered to BNS 196; substance unchanged."),
    ("153A","196",   "Promoting enmity between different groups on grounds of religion, race, etc.",
     "substantive_change",
     "Renumbered to BNS 196. BNS expressly includes electronic media and social media posts as means of promoting enmity. Punishment (up to 3 years; up to 5 years if in place of worship) unchanged."),
    ("153B","197",   "Imputations, assertions prejudicial to national-integration",
     "renumbering_only",
     "Renumbered to BNS 197; substance unchanged."),
    ("154", "198",   "Owner or occupier of land on which an unlawful assembly is held",
     "renumbering_only",
     "Renumbered to BNS 198; substance unchanged."),
    ("155", "199",   "Liability of person for whose benefit riot is committed",
     "renumbering_only",
     "Renumbered to BNS 199; substance unchanged."),
    ("156", "200",   "Liability of agent of owner or occupier for whose benefit riot is committed",
     "renumbering_only",
     "Renumbered to BNS 200; substance unchanged."),
    ("157", "201",   "Harbouring persons hired for an unlawful assembly",
     "renumbering_only",
     "Renumbered to BNS 201; substance unchanged."),
    ("158", "202",   "Being hired to take part in an unlawful assembly or riot",
     "renumbering_only",
     "Renumbered to BNS 202; substance unchanged."),
    ("159", "189",   "Affray",
     "renumbering_only",
     "Renumbered to BNS 189 (definition section); affray definition absorbed."),
    ("160", "203",   "Punishment for committing affray",
     "renumbering_only",
     "Renumbered to BNS 203; punishment for affray (up to 1 month, or fine up to Rs 200) unchanged."),

    # ── CHAPTER IX  OFFENCES BY OR RELATING TO PUBLIC SERVANTS (IPC 161-171) ─
    ("161", None,    "Public servant taking gratification other than legal remuneration",
     "deleted",
     "Deleted from BNS. Moved to Prevention of Corruption Act 1988 (as amended). Advocates must now cite PoCA 1988, not IPC 161."),
    ("162", None,    "Taking gratification in order to influence public servant by corrupt or illegal means",
     "deleted",
     "Deleted. Moved to Prevention of Corruption Act 1988."),
    ("163", None,    "Taking gratification for exercise of personal influence with public servant",
     "deleted",
     "Deleted. Moved to Prevention of Corruption Act 1988."),
    ("164", None,    "Punishment for abetment by public servant of offences defined in section 162 or 163",
     "deleted",
     "Deleted. Moved to Prevention of Corruption Act 1988."),
    ("165", None,    "Public servant obtaining valuable thing, without consideration, from person concerned in proceeding",
     "deleted",
     "Deleted. Moved to Prevention of Corruption Act 1988."),
    ("165A",None,    "Punishment for abetment of offences defined in section 165",
     "deleted",
     "Deleted. Moved to Prevention of Corruption Act 1988."),
    ("166", "198",   "Public servant disobeying law, with intent to cause injury to any person",
     "renumbering_only",
     "Renumbered to BNS 198; substance unchanged."),
    ("166A","202",   "Public servant disobeying direction under law",
     "renumbering_only",
     "Renumbered to BNS 202; covers police officers failing to record FIR for rape/acid attack victims. Rigorous imprisonment 6 months to 2 years + fine."),
    ("166B","203",   "Punishment for non-treatment of victim",
     "renumbering_only",
     "Renumbered to BNS 203; substance unchanged — hospitals cannot refuse first-aid to victims of offences."),
    ("167", "204",   "Public servant framing an incorrect document with intent to cause injury",
     "renumbering_only",
     "Renumbered to BNS 204; substance unchanged."),
    ("168", "205",   "Public servant unlawfully engaging in trade",
     "renumbering_only",
     "Renumbered to BNS 205; substance unchanged."),
    ("169", "206",   "Public servant unlawfully buying or bidding for property",
     "renumbering_only",
     "Renumbered to BNS 206; substance unchanged."),
    ("170", "207",   "Personating a public servant",
     "renumbering_only",
     "Renumbered to BNS 207; substance unchanged."),
    ("171", "208",   "Wearing garb or carrying token used by public servant with fraudulent intent",
     "renumbering_only",
     "Renumbered to BNS 208; substance unchanged."),

    # ── CHAPTER X  CONTEMPTS OF LAWFUL AUTHORITY (IPC 172-190) ───────────────
    ("172", "209",   "Absconding to avoid service of summons or other proceeding",
     "renumbering_only",
     "Renumbered to BNS 209; substance unchanged."),
    ("173", "210",   "Preventing service of summons or other proceeding",
     "renumbering_only",
     "Renumbered to BNS 210; substance unchanged."),
    ("174", "211",   "Non-attendance in obedience to an order from public servant",
     "renumbering_only",
     "Renumbered to BNS 211; substance unchanged."),
    ("174A","212",   "Non-appearance in response to a proclamation under section 82 CrPC",
     "substantive_change",
     "Renumbered to BNS 212. Cross-reference updated from CrPC 82 to BNSS 84."),
    ("175", "213",   "Omission to produce document to public servant by person legally bound to produce it",
     "renumbering_only",
     "Renumbered to BNS 213; substance unchanged."),
    ("176", "214",   "Omission to give notice or information to public servant by person legally bound",
     "renumbering_only",
     "Renumbered to BNS 214; substance unchanged."),
    ("177", "215",   "Furnishing false information",
     "renumbering_only",
     "Renumbered to BNS 215; substance unchanged."),
    ("178", "216",   "Refusing oath or affirmation when duly required by public servant to make it",
     "renumbering_only",
     "Renumbered to BNS 216; substance unchanged."),
    ("179", "217",   "Refusing to answer public servant authorized to question",
     "renumbering_only",
     "Renumbered to BNS 217; substance unchanged."),
    ("180", "218",   "Refusing to sign statement",
     "renumbering_only",
     "Renumbered to BNS 218; substance unchanged."),
    ("181", "219",   "False statement on oath or affirmation to public servant or person authorized to administer an oath",
     "renumbering_only",
     "Renumbered to BNS 219; substance unchanged."),
    ("182", "220",   "False information, with intent to cause public servant to use his lawful power to the injury of another person",
     "renumbering_only",
     "Renumbered to BNS 220; substance unchanged."),
    ("183", "221",   "Resistance to the taking of property by the lawful authority of a public servant",
     "renumbering_only",
     "Renumbered to BNS 221; substance unchanged."),
    ("184", "222",   "Obstructing sale of property offered for sale by authority of public servant",
     "renumbering_only",
     "Renumbered to BNS 222; substance unchanged."),
    ("185", "223",   "Illegal purchase or bid for property offered for sale by authority of public servant",
     "renumbering_only",
     "Renumbered to BNS 223; substance unchanged."),
    ("186", "224",   "Obstructing public servant in discharge of public functions",
     "renumbering_only",
     "Renumbered to BNS 224; punishment (up to 3 months, or fine up to Rs 2,500) unchanged."),
    ("187", "225",   "Omission to assist public servant when bound by law to give assistance",
     "renumbering_only",
     "Renumbered to BNS 225; substance unchanged."),
    ("188", "226",   "Disobedience to order duly promulgated by public servant",
     "renumbering_only",
     "Renumbered to BNS 226; substance unchanged."),
    ("189", "227",   "Threat of injury to public servant",
     "renumbering_only",
     "Renumbered to BNS 227; substance unchanged."),
    ("190", "228",   "Threat of injury to induce person to refrain from applying for protection to public servant",
     "renumbering_only",
     "Renumbered to BNS 228; substance unchanged."),

    # ── CHAPTER XI  FALSE EVIDENCE (IPC 191-229) ──────────────────────────────
    ("191", "229",   "Giving false evidence",
     "renumbering_only",
     "Renumbered to BNS 229; substance unchanged."),
    ("192", "230",   "Fabricating false evidence",
     "renumbering_only",
     "Renumbered to BNS 230; substance unchanged."),
    ("193", "231",   "Punishment for false evidence",
     "renumbering_only",
     "Renumbered to BNS 231; punishment (up to 7 years + fine for judicial proceedings; up to 3 years for others) unchanged."),
    ("194", "232",   "Giving or fabricating false evidence with intent to procure conviction of capital offence",
     "renumbering_only",
     "Renumbered to BNS 232; substance unchanged."),
    ("195", "233",   "Giving or fabricating false evidence with intent to procure conviction of offence punishable with imprisonment for life or imprisonment",
     "renumbering_only",
     "Renumbered to BNS 233; substance unchanged."),
    ("195A","234",   "Threatening any person to give false evidence",
     "renumbering_only",
     "Renumbered to BNS 234; substance unchanged."),
    ("196", "235",   "Using evidence known to be false",
     "renumbering_only",
     "Renumbered to BNS 235; substance unchanged."),
    ("197", "236",   "Issuing or signing false certificate",
     "renumbering_only",
     "Renumbered to BNS 236; substance unchanged."),
    ("198", "237",   "Using as true a certificate known to be false",
     "renumbering_only",
     "Renumbered to BNS 237; substance unchanged."),
    ("199", "238",   "False statement made in declaration which is by law receivable as evidence",
     "renumbering_only",
     "Renumbered to BNS 238; substance unchanged."),
    ("200", "239",   "Using as true such declaration knowing it to be false",
     "renumbering_only",
     "Renumbered to BNS 239; substance unchanged."),
    ("201", "240",   "Causing disappearance of evidence of offence, or giving false information to screen offender",
     "renumbering_only",
     "Renumbered to BNS 240; substance unchanged."),
    ("202", "241",   "Intentional omission to give information of offence by person bound to inform",
     "renumbering_only",
     "Renumbered to BNS 241; substance unchanged."),
    ("203", "242",   "Giving false information respecting an offence committed",
     "renumbering_only",
     "Renumbered to BNS 242; substance unchanged."),
    ("204", "243",   "Destruction of document to prevent its production as evidence",
     "renumbering_only",
     "Renumbered to BNS 243; substance unchanged."),
    ("205", "244",   "False personation for purpose of act or proceeding in suit or prosecution",
     "renumbering_only",
     "Renumbered to BNS 244; substance unchanged."),
    ("206", "245",   "Fraudulent removal or concealment of property to prevent its seizure as forfeited",
     "renumbering_only",
     "Renumbered to BNS 245; substance unchanged."),
    ("207", "246",   "Fraudulent claim to property to prevent its seizure as forfeited",
     "renumbering_only",
     "Renumbered to BNS 246; substance unchanged."),
    ("208", "247",   "Fraudulently suffering decree for sum not due",
     "renumbering_only",
     "Renumbered to BNS 247; substance unchanged."),
    ("209", "248",   "Dishonestly making false claim in Court",
     "renumbering_only",
     "Renumbered to BNS 248; substance unchanged."),
    ("210", "249",   "Fraudulently obtaining decree for sum not due",
     "renumbering_only",
     "Renumbered to BNS 249; substance unchanged."),
    ("211", "250",   "False charge of offence made with intent to injure",
     "renumbering_only",
     "Renumbered to BNS 250; substance unchanged."),
    ("212", "251",   "Harbouring offender",
     "renumbering_only",
     "Renumbered to BNS 251; substance unchanged."),
    ("213", "252",   "Taking gift, etc., to screen an offender from punishment",
     "renumbering_only",
     "Renumbered to BNS 252; substance unchanged."),
    ("214", "253",   "Offering gift or restoration of stolen property on condition of not prosecuting",
     "renumbering_only",
     "Renumbered to BNS 253; substance unchanged."),
    ("215", "254",   "Taking gift to help to recover stolen property, etc.",
     "renumbering_only",
     "Renumbered to BNS 254; substance unchanged."),
    ("216", "255",   "Harbouring offender who has escaped from custody or whose apprehension has been ordered",
     "renumbering_only",
     "Renumbered to BNS 255; substance unchanged."),
    ("216A","256",   "Penalty for harbouring robbers or dacoits",
     "renumbering_only",
     "Renumbered to BNS 256; substance unchanged."),
    ("217", "257",   "Public servant disobeying direction of law with intent to save person from punishment",
     "renumbering_only",
     "Renumbered to BNS 257; substance unchanged."),
    ("218", "258",   "Public servant framing incorrect record or writing with intent to save person from punishment",
     "renumbering_only",
     "Renumbered to BNS 258; substance unchanged."),
    ("219", "259",   "Public servant in judicial proceeding corruptly making report, etc., contrary to law",
     "renumbering_only",
     "Renumbered to BNS 259; substance unchanged."),
    ("220", "260",   "Commitment for trial or confinement by person having authority who knows that he is acting contrary to law",
     "renumbering_only",
     "Renumbered to BNS 260; substance unchanged."),
    ("221", "261",   "Intentional omission to apprehend on the part of public servant bound to apprehend",
     "renumbering_only",
     "Renumbered to BNS 261; substance unchanged."),
    ("222", "262",   "Intentional omission to apprehend on the part of public servant bound to apprehend person under sentence",
     "renumbering_only",
     "Renumbered to BNS 262; substance unchanged."),
    ("223", "263",   "Escape from confinement or custody negligently suffered by public servant",
     "renumbering_only",
     "Renumbered to BNS 263; substance unchanged."),
    ("224", "264",   "Resistance or obstruction by a person to his lawful apprehension",
     "renumbering_only",
     "Renumbered to BNS 264; substance unchanged."),
    ("225", "265",   "Resistance or obstruction to lawful apprehension of another person",
     "renumbering_only",
     "Renumbered to BNS 265; substance unchanged."),
    ("225A","266",   "Omission to apprehend, or sufferance of escape, on part of public servant, in cases not otherwise provided for",
     "renumbering_only",
     "Renumbered to BNS 266; substance unchanged."),
    ("225B","267",   "Resistance or obstruction to lawful apprehension, or escape or rescue in cases not otherwise provided for",
     "renumbering_only",
     "Renumbered to BNS 267; substance unchanged."),
    ("226", None,    "Unlawful return from transportation",
     "deleted",
     "Deleted. Transportation as a punishment was abolished; this provision became redundant."),
    ("227", "268",   "Violation of condition of remission of punishment",
     "renumbering_only",
     "Renumbered to BNS 268; substance unchanged."),
    ("228", "269",   "Intentional insult or interruption to public servant sitting in judicial proceeding",
     "renumbering_only",
     "Renumbered to BNS 269; substance unchanged."),
    ("228A","270",   "Disclosure of identity of the victim of certain offences",
     "renumbering_only",
     "Renumbered to BNS 270; protects identity of rape, sexual harassment, and trafficking victims. Substance unchanged."),
    ("229", "271",   "Personation of a juror or assessor",
     "renumbering_only",
     "Renumbered to BNS 271; substance unchanged."),

    # ── CHAPTER XII  COIN AND GOVERNMENT STAMPS (IPC 230-263A) ───────────────
    ("230", "174",   "Coin — definition",
     "substantive_change",
     "Renumbered to BNS 174. BNS updates definition to include digital currency and cryptocurrency in addition to metal coins."),
    ("231", "175",   "Counterfeiting coin",
     "renumbering_only",
     "Renumbered to BNS 175; substance unchanged."),
    ("232", "176",   "Counterfeiting Indian coin",
     "renumbering_only",
     "Renumbered to BNS 176; enhanced punishment retained (up to 10 years + fine)."),
    ("233", "177",   "Making or selling instrument for counterfeiting coin",
     "renumbering_only",
     "Renumbered to BNS 177; substance unchanged."),
    ("234", "178",   "Making or selling instrument for counterfeiting Indian coin",
     "renumbering_only",
     "Renumbered to BNS 178; substance unchanged."),
    ("235", "179",   "Possession of instrument or material for purpose of using the same for counterfeiting coin",
     "renumbering_only",
     "Renumbered to BNS 179; substance unchanged."),
    ("236", "180",   "Abetting in India the counterfeiting out of India of coin",
     "renumbering_only",
     "Renumbered to BNS 180; substance unchanged."),
    ("237", "181",   "Import or export of counterfeit coin",
     "renumbering_only",
     "Renumbered to BNS 181; substance unchanged."),
    ("238", "182",   "Import or export of counterfeits of the Indian coin",
     "renumbering_only",
     "Renumbered to BNS 182; substance unchanged."),
    ("239", "183",   "Having possession of counterfeit coin",
     "renumbering_only",
     "Renumbered to BNS 183; substance unchanged."),
    ("240", "184",   "Having possession of Indian coin which has been counterfeited",
     "renumbering_only",
     "Renumbered to BNS 184; substance unchanged."),
    ("241", "185",   "Fraudulently or dishonestly diminishing weight or altering composition of coin",
     "renumbering_only",
     "Renumbered to BNS 185; substance unchanged."),
    ("242", "186",   "Altering appearance of coin to resemble a different coin",
     "renumbering_only",
     "Renumbered to BNS 186; substance unchanged."),
    ("243", "187",   "Having possession of coin with intent to use as a genuine coin",
     "renumbering_only",
     "Renumbered to BNS 187; substance unchanged."),
    ("244", "188",   "Person employed in mint causing coin to be of different weight or composition",
     "renumbering_only",
     "Renumbered to BNS 188; substance unchanged."),
    ("245", "189",   "Unlawfully taking coining instruments from mint",
     "renumbering_only",
     "Renumbered to BNS 189; substance unchanged."),
    ("246", "190",   "Fraudulently or dishonestly diminishing weight or altering composition of currency-notes or bank-notes",
     "renumbering_only",
     "Renumbered to BNS 190; substance unchanged."),
    ("247", "191",   "Fraudulently or dishonestly using as genuine such altered coin",
     "renumbering_only",
     "Renumbered to BNS 191; substance unchanged."),
    ("248", "192",   "Altering appearance of currency-notes or bank-notes",
     "renumbering_only",
     "Renumbered to BNS 192; substance unchanged."),
    ("249", "193",   "Having possession of coin, the clipping etc. of which constitutes an offence",
     "renumbering_only",
     "Renumbered to BNS 193; substance unchanged."),
    ("250", "194",   "Having possession of Indian coin in altered state",
     "renumbering_only",
     "Renumbered to BNS 194; substance unchanged."),
    ("251", "195",   "Fraudulently or dishonestly using such altered coin",
     "renumbering_only",
     "Renumbered to BNS 195; substance unchanged."),
    ("252", "196",   "Possession of forged or counterfeit currency-notes or bank-notes",
     "renumbering_only",
     "Renumbered to BNS 196; substance unchanged."),
    ("253", "197",   "Counterfeiting government stamp",
     "renumbering_only",
     "Renumbered to BNS 197; substance unchanged."),
    ("254", "198",   "Having possession of instrument or material for counterfeiting government stamp",
     "renumbering_only",
     "Renumbered to BNS 198; substance unchanged."),
    ("255", "199",   "Making or selling instrument for counterfeiting government stamp",
     "renumbering_only",
     "Renumbered to BNS 199; substance unchanged."),
    ("256", "200",   "Sale of counterfeit government stamp",
     "renumbering_only",
     "Renumbered to BNS 200; substance unchanged."),
    ("257", "201",   "Having possession of a counterfeit government stamp",
     "renumbering_only",
     "Renumbered to BNS 201; substance unchanged."),
    ("258", "202",   "Using as genuine a government stamp known to be counterfeit",
     "renumbering_only",
     "Renumbered to BNS 202; substance unchanged."),
    ("259", "203",   "Effacing writing from substance bearing government stamp",
     "renumbering_only",
     "Renumbered to BNS 203; substance unchanged."),
    ("260", "204",   "Using a government stamp known to have been before used",
     "renumbering_only",
     "Renumbered to BNS 204; substance unchanged."),
    ("261", "205",   "Erasure of mark denoting that stamp has been used",
     "renumbering_only",
     "Renumbered to BNS 205; substance unchanged."),
    ("262", "206",   "Prohibition of fictitious stamps",
     "renumbering_only",
     "Renumbered to BNS 206; substance unchanged."),
    ("263", "207",   "Fraudulent use, removal, disposal of a used stamp",
     "renumbering_only",
     "Renumbered to BNS 207; substance unchanged."),
    ("263A",None,    "Prohibition of fictitious stamps (Indian Stamp Act)",
     "deleted",
     "Deleted from BNS; governed entirely by the Indian Stamp Act 1899 and its state equivalents."),

    # ── CHAPTER XIII  WEIGHTS AND MEASURES (IPC 264-267) ──────────────────────
    ("264", "293",   "Fraudulent use of false instrument for weighing",
     "renumbering_only",
     "Renumbered to BNS 293; substance unchanged."),
    ("265", "294",   "Fraudulent use of false weight or measure",
     "renumbering_only",
     "Renumbered to BNS 294; substance unchanged."),
    ("266", "295",   "Being in possession of false weight or measure",
     "renumbering_only",
     "Renumbered to BNS 295; substance unchanged."),
    ("267", "296",   "Making or selling false weight or measure",
     "renumbering_only",
     "Renumbered to BNS 296; substance unchanged."),

    # ── CHAPTER XIV  PUBLIC HEALTH, SAFETY, DECENCY AND MORALITY (IPC 268-294B)
    ("268", "272",   "Public nuisance",
     "renumbering_only",
     "Renumbered to BNS 272; definition of public nuisance unchanged."),
    ("269", "273",   "Negligent act likely to spread infection of disease dangerous to life",
     "renumbering_only",
     "Renumbered to BNS 273; punishment (up to 6 months, or fine, or both) unchanged."),
    ("270", "274",   "Malignant act likely to spread infection of disease dangerous to life",
     "renumbering_only",
     "Renumbered to BNS 274; punishment (up to 2 years) unchanged."),
    ("271", "275",   "Disobedience to quarantine rule",
     "renumbering_only",
     "Renumbered to BNS 275; substance unchanged. Became significant during COVID-19."),
    ("272", "276",   "Adulteration of food or drink which is intended for sale",
     "renumbering_only",
     "Renumbered to BNS 276; substance unchanged."),
    ("273", "277",   "Sale of noxious food or drink",
     "renumbering_only",
     "Renumbered to BNS 277; substance unchanged."),
    ("274", "278",   "Adulteration of drugs",
     "renumbering_only",
     "Renumbered to BNS 278; substance unchanged."),
    ("275", "279",   "Sale of adulterated drugs",
     "renumbering_only",
     "Renumbered to BNS 279; substance unchanged."),
    ("276", "280",   "Sale of drug as a different drug or preparation",
     "renumbering_only",
     "Renumbered to BNS 280; substance unchanged."),
    ("277", "281",   "Fouling water of public spring or reservoir",
     "renumbering_only",
     "Renumbered to BNS 281; substance unchanged."),
    ("278", "282",   "Making atmosphere noxious to health",
     "renumbering_only",
     "Renumbered to BNS 282; substance unchanged."),
    ("279", "283",   "Rash driving or riding on a public way",
     "renumbering_only",
     "Renumbered to BNS 283; substance unchanged."),
    ("280", "284",   "Rash navigation of vessel",
     "renumbering_only",
     "Renumbered to BNS 284; substance unchanged."),
    ("281", "285",   "Exhibition of false light, mark or buoy",
     "renumbering_only",
     "Renumbered to BNS 285; substance unchanged."),
    ("282", "286",   "Conveying person by water for hire in unsafe or overloaded vessel",
     "renumbering_only",
     "Renumbered to BNS 286; substance unchanged."),
    ("283", "287",   "Danger or obstruction in public way or line of navigation",
     "renumbering_only",
     "Renumbered to BNS 287; substance unchanged."),
    ("284", "288",   "Negligent conduct with respect to poisonous substance",
     "renumbering_only",
     "Renumbered to BNS 288; substance unchanged."),
    ("285", "289",   "Negligent conduct with respect to fire or combustible matter",
     "renumbering_only",
     "Renumbered to BNS 289; substance unchanged."),
    ("286", "290",   "Negligent conduct with respect to explosive substance",
     "renumbering_only",
     "Renumbered to BNS 290; substance unchanged."),
    ("287", "291",   "Negligent conduct with respect to machinery",
     "renumbering_only",
     "Renumbered to BNS 291; substance unchanged."),
    ("288", "292",   "Negligent conduct with respect to pulling down or repairing buildings",
     "renumbering_only",
     "Renumbered to BNS 292; substance unchanged."),
    ("289", "288",   "Negligent conduct with respect to animal",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("290", "272",   "Punishment for public nuisance in cases not otherwise provided for",
     "renumbering_only",
     "Renumbered; punishment (fine up to Rs 200) unchanged."),
    ("291", "273",   "Continuance of nuisance after injunction to discontinue",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("292", "293",   "Sale, etc., of obscene books, etc.",
     "substantive_change",
     "Renumbered. BNS adds online distribution, digital obscene content, and streaming as covered acts. Punishment enhanced."),
    ("292A",None,    "Printing, etc., of grossly indecent or scurrilous matter",
     "deleted",
     "Deleted from BNS; substantially covered by IT Act 2000 and the broadened BNS 293."),
    ("293", "294",   "Sale, etc., of obscene objects to young person",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("294", "295",   "Obscene acts and songs",
     "renumbering_only",
     "Renumbered to BNS 295; substance unchanged."),
    ("294A","296",   "Keeping lottery office",
     "renumbering_only",
     "Renumbered to BNS 296; substance unchanged."),
    ("294B",None,    "Lotteries not authorised by State Government",
     "deleted",
     "Deleted from BNS; governed by state lottery laws and the Lotteries (Regulation) Act 1998."),

    # ── CHAPTER XV  OFFENCES RELATING TO RELIGION (IPC 295-298) ──────────────
    ("295", "297",   "Injuring or defiling place of worship, with intent to insult religion",
     "renumbering_only",
     "Renumbered to BNS 297; substance unchanged."),
    ("295A","299",   "Deliberate and malicious acts, intended to outrage religious feelings",
     "renumbering_only",
     "Renumbered to BNS 299; punishment (up to 3 years, or fine, or both) unchanged."),
    ("296", "298",   "Disturbing religious assembly",
     "renumbering_only",
     "Renumbered to BNS 298; substance unchanged."),
    ("297", "300",   "Trespassing on burial places, etc.",
     "renumbering_only",
     "Renumbered to BNS 300; substance unchanged."),
    ("298", "302",   "Uttering, words, etc., with deliberate intent to wound the religious feelings of any person",
     "renumbering_only",
     "Renumbered to BNS 302; punishment (up to 1 year, or fine, or both) unchanged."),

    # ── CHAPTER XVI  OFFENCES AFFECTING THE HUMAN BODY (IPC 299-377) ─────────
    ("299", "99",    "Culpable homicide",
     "renumbering_only",
     "Renumbered to BNS 99; definition of culpable homicide unchanged."),
    ("300", "100",   "Murder",
     "renumbering_only",
     "Renumbered to BNS 100; definition and five exceptions unchanged."),
    ("301", "102",   "Culpable homicide by causing death of person other than person whose death was intended",
     "renumbering_only",
     "Renumbered to BNS 102; substance unchanged."),
    ("302", "103(1)","Punishment for murder",
     "substantive_change",
     "Renumbered to BNS 103(1). Punishment (death or imprisonment for life + fine) unchanged. BNS adds a new sub-section for murder committed by a group of five or more persons on grounds of race, caste, community, sex, place of birth, language, or personal belief — mandates minimum 7 years, up to life or death."),
    ("303", "103(2)","Punishment for murder by life-convict",
     "renumbering_only",
     "Renumbered to BNS 103(2); punishment (death) unchanged."),
    ("304", "105",   "Punishment for culpable homicide not amounting to murder",
     "renumbering_only",
     "Renumbered to BNS 105; two-part punishment structure (Part I: life or 10 years; Part II: 10 years) unchanged."),
    ("304A","106",   "Causing death by negligence",
     "substantive_change",
     "Renumbered to BNS 106. Substantive change: BNS 106(1) adds a specific provision for registered medical practitioners — punishment up to 2 years + fine. BNS 106(2) creates a new enhanced offence for hit-and-run death (fleeing without reporting) — punishment up to 10 years + fine."),
    ("304B","80",    "Dowry death",
     "renumbering_only",
     "Moved to BNS 80 (marriage-related offences chapter). Minimum 7-year punishment and definition unchanged."),
    ("305", "107",   "Abetment of suicide of child or insane person",
     "renumbering_only",
     "Renumbered to BNS 107; punishment (death or life or up to 10 years + fine) unchanged."),
    ("306", "108",   "Abetment of suicide",
     "renumbering_only",
     "Renumbered to BNS 108; punishment (up to 10 years + fine) unchanged."),
    ("307", "109",   "Attempt to murder",
     "renumbering_only",
     "Renumbered to BNS 109; punishment (up to 10 years; life if hurt caused) unchanged. Attempt by a life convict retains death penalty option."),
    ("308", "110",   "Attempt to commit culpable homicide",
     "renumbering_only",
     "Renumbered to BNS 110; punishment (up to 3 years; up to 7 years if hurt caused) unchanged."),
    ("309", None,    "Attempt to commit suicide",
     "deleted",
     "DELETED from BNS. Attempt to commit suicide is no longer a criminal offence under BNS. This aligns with the Mental Healthcare Act 2017, Section 115, which creates a rebuttable presumption that a person who attempts suicide is under severe stress. The state now has a duty to provide care and rehabilitation."),
    ("310", "112",   "Thug",
     "renumbering_only",
     "Renumbered to BNS 112; substance unchanged."),
    ("311", "113",   "Punishment of Thug",
     "renumbering_only",
     "Renumbered to BNS 113; life imprisonment for Thugs unchanged."),
    ("312", "88",    "Causing miscarriage",
     "renumbering_only",
     "Moved to BNS 88 (marriage/family offences chapter). Punishment (up to 3 years; up to 7 years if quickened) unchanged. Note: Medical Termination of Pregnancy Act 1971 governs lawful abortions."),
    ("313", "89",    "Causing miscarriage without woman's consent",
     "renumbering_only",
     "Renumbered to BNS 89; punishment (up to 10 years or life) unchanged."),
    ("314", "90",    "Death of woman caused by act done with intent to cause miscarriage",
     "renumbering_only",
     "Renumbered to BNS 90; substance unchanged."),
    ("315", "91",    "Act done with intent to prevent child being born alive or to cause it to die after birth",
     "renumbering_only",
     "Renumbered to BNS 91; substance unchanged."),
    ("316", "92",    "Causing death of quick unborn child by act amounting to culpable homicide",
     "renumbering_only",
     "Renumbered to BNS 92; substance unchanged."),
    ("317", "93",    "Exposure and abandonment of child under twelve years, by parent or person having care of it",
     "renumbering_only",
     "Renumbered to BNS 93; substance unchanged."),
    ("318", "94",    "Concealment of birth by secret disposal of dead body",
     "renumbering_only",
     "Renumbered to BNS 94; substance unchanged."),
    ("319", "113",   "Hurt",
     "renumbering_only",
     "Renumbered to BNS 113; definition of hurt unchanged."),
    ("320", "114",   "Grievous hurt",
     "substantive_change",
     "Renumbered to BNS 114. Substantive change: BNS adds 'permanent damage to the brain or any part of the body' as a ninth kind of grievous hurt (IPC had 8 categories). All original eight categories retained."),
    ("321", "115",   "Voluntarily causing hurt",
     "renumbering_only",
     "Renumbered to BNS 115; definition unchanged."),
    ("322", "116",   "Voluntarily causing grievous hurt",
     "renumbering_only",
     "Renumbered to BNS 116; definition unchanged."),
    ("323", "115(2)","Punishment for voluntarily causing hurt",
     "renumbering_only",
     "Renumbered to BNS 115(2); punishment (up to 1 year, or fine up to Rs 10,000) unchanged."),
    ("324", "117(2)","Voluntarily causing hurt by dangerous weapons or means",
     "renumbering_only",
     "Renumbered to BNS 117(2); punishment (up to 3 years, or fine, or both) unchanged."),
    ("325", "116(2)","Punishment for voluntarily causing grievous hurt",
     "renumbering_only",
     "Renumbered to BNS 116(2); punishment (up to 7 years + fine) unchanged."),
    ("326", "117(3)","Voluntarily causing grievous hurt by dangerous weapons or means",
     "renumbering_only",
     "Renumbered to BNS 117(3); punishment (up to 10 years + fine) unchanged."),
    ("326A","124",   "Voluntarily causing grievous hurt by use of acid, etc.",
     "substantive_change",
     "Renumbered to BNS 124. BNS adds a mandatory clause requiring courts to award compensation to the victim for medical expenses. Minimum 10 years (up to life) retained."),
    ("326B","125",   "Voluntarily throwing or attempting to throw acid",
     "renumbering_only",
     "Renumbered to BNS 125; punishment (5 to 7 years + fine) unchanged."),
    ("327", "118",   "Voluntarily causing hurt to extort property, or to constrain to an illegal act",
     "renumbering_only",
     "Renumbered to BNS 118; substance unchanged."),
    ("328", "119",   "Causing hurt by means of poison, etc., with intent to commit an offence",
     "renumbering_only",
     "Renumbered to BNS 119; substance unchanged."),
    ("329", "120",   "Voluntarily causing grievous hurt to extort property, or to constrain to an illegal act",
     "renumbering_only",
     "Renumbered to BNS 120; substance unchanged."),
    ("330", "121",   "Voluntarily causing hurt to extort confession, or to compel restoration of property",
     "renumbering_only",
     "Renumbered to BNS 121; custodial torture covered — punishment up to 7 years unchanged."),
    ("331", "122",   "Voluntarily causing grievous hurt to extort confession, or to compel restoration of property",
     "renumbering_only",
     "Renumbered to BNS 122; substance unchanged."),
    ("332", "123",   "Voluntarily causing hurt to deter public servant from his duty",
     "renumbering_only",
     "Renumbered to BNS 123; substance unchanged."),
    ("333", "123",   "Voluntarily causing grievous hurt to deter public servant from his duty",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("334", "115",   "Voluntarily causing hurt on provocation",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("335", "116",   "Voluntarily causing grievous hurt on provocation",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("336", "125",   "Act endangering life or personal safety of others",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("337", "125",   "Causing hurt by act endangering life or personal safety of others",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("338", "125",   "Causing grievous hurt by act endangering life or personal safety of others",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("339", "126",   "Wrongful restraint",
     "renumbering_only",
     "Renumbered to BNS 126; definition unchanged."),
    ("340", "127",   "Wrongful confinement",
     "renumbering_only",
     "Renumbered to BNS 127; definition unchanged."),
    ("341", "126",   "Punishment for wrongful restraint",
     "renumbering_only",
     "Renumbered; punishment (up to 1 month, or fine up to Rs 500) unchanged."),
    ("342", "127",   "Punishment for wrongful confinement",
     "renumbering_only",
     "Renumbered; punishment (up to 1 year, or fine up to Rs 5,000) unchanged."),
    ("343", "127",   "Wrongful confinement for three or more days",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("344", "127",   "Wrongful confinement for ten or more days",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("345", "127",   "Wrongful confinement of person for whose liberation writ has been issued",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("346", "127",   "Wrongful confinement in secret",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("347", "128",   "Wrongful confinement to extort property, or constrain to illegal act",
     "renumbering_only",
     "Renumbered to BNS 128; substance unchanged."),
    ("348", "129",   "Wrongful confinement to extort confession, or compel restoration of property",
     "renumbering_only",
     "Renumbered to BNS 129; substance unchanged."),
    ("349", "130",   "Force",
     "renumbering_only",
     "Renumbered to BNS 130; definition of force unchanged."),
    ("350", "131",   "Criminal force",
     "renumbering_only",
     "Renumbered to BNS 131; definition unchanged."),
    ("351", "132",   "Assault",
     "renumbering_only",
     "Renumbered to BNS 132; definition of assault unchanged."),
    ("352", "132",   "Punishment for assault or criminal force otherwise than on grave provocation",
     "renumbering_only",
     "Renumbered; punishment (up to 3 months, or fine up to Rs 500) unchanged."),
    ("353", "133",   "Assault or criminal force to deter public servant from discharge of his duty",
     "renumbering_only",
     "Renumbered to BNS 133; substance unchanged."),
    ("354", "74",    "Assault or criminal force to woman with intent to outrage her modesty",
     "renumbering_only",
     "Renumbered to BNS 74; minimum 1-year punishment (up to 5 years) unchanged."),
    ("354A","75",    "Sexual harassment and punishment for sexual harassment",
     "renumbering_only",
     "Renumbered to BNS 75; covers unwelcome physical contact, sexual favours, pornography, sexually coloured remarks. Punishment unchanged."),
    ("354B","76",    "Assault or use of criminal force to woman with intent to disrobe",
     "renumbering_only",
     "Renumbered to BNS 76; minimum 3-year punishment (up to 7 years) unchanged."),
    ("354C","77",    "Voyeurism",
     "renumbering_only",
     "Renumbered to BNS 77; first conviction 1–3 years; subsequent 3–7 years. Unchanged."),
    ("354D","78",    "Stalking",
     "renumbering_only",
     "Renumbered to BNS 78; first offence up to 3 years; repeat up to 5 years. Unchanged."),
    ("355", "134",   "Assault or criminal force with intent to dishonour person, otherwise than on grave provocation",
     "renumbering_only",
     "Renumbered to BNS 134; substance unchanged."),
    ("356", "135",   "Assault or criminal force in attempt to commit theft of property carried by a person",
     "renumbering_only",
     "Renumbered to BNS 135; substance unchanged."),
    ("357", "136",   "Assault or criminal force in attempt wrongfully to confine a person",
     "renumbering_only",
     "Renumbered to BNS 136; substance unchanged."),
    ("358", "132",   "Assault or criminal force on grave provocation",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("359", "137",   "Kidnapping",
     "renumbering_only",
     "Renumbered to BNS 137; two types (from India and from lawful guardianship) unchanged."),
    ("360", "137",   "Kidnapping from India",
     "renumbering_only",
     "Renumbered; definition merged into BNS 137."),
    ("361", "137",   "Kidnapping from lawful guardianship",
     "renumbering_only",
     "Renumbered; definition merged into BNS 137. Age threshold: under 16 (boy) or under 18 (girl) unchanged."),
    ("362", "138",   "Abduction",
     "renumbering_only",
     "Renumbered to BNS 138; definition of abduction unchanged."),
    ("363", "137(2)","Punishment for kidnapping",
     "renumbering_only",
     "Renumbered to BNS 137(2); punishment (up to 7 years + fine) unchanged."),
    ("363A","139",   "Kidnapping or maiming a minor for purposes of begging",
     "renumbering_only",
     "Renumbered to BNS 139; substance unchanged."),
    ("364", "140",   "Kidnapping or abducting in order to murder",
     "renumbering_only",
     "Renumbered to BNS 140; punishment (life or rigorous imprisonment up to 10 years + fine) unchanged."),
    ("364A","140",   "Kidnapping for ransom, etc.",
     "substantive_change",
     "Renumbered to BNS 140. BNS adds organised crime group kidnappings as an aggravated form. Death or life imprisonment."),
    ("365", "141",   "Kidnapping or abducting with intent secretly and wrongfully to confine person",
     "renumbering_only",
     "Renumbered to BNS 141; substance unchanged."),
    ("366", "142",   "Kidnapping, abducting or inducing woman to compel her marriage, etc.",
     "renumbering_only",
     "Renumbered to BNS 142; punishment (up to 10 years + fine) unchanged."),
    ("366A","142",   "Procuration of minor girl",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("366B","142",   "Importation of girl from foreign country",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("367", "144",   "Kidnapping or abducting in order to subject person to grievous hurt, slavery, etc.",
     "renumbering_only",
     "Renumbered to BNS 144; substance unchanged."),
    ("368", "145",   "Wrongfully concealing or keeping in confinement, kidnapped or abducted person",
     "renumbering_only",
     "Renumbered to BNS 145; substance unchanged."),
    ("369", "146",   "Kidnapping or abducting child under ten years with intent to steal from its person",
     "renumbering_only",
     "Renumbered to BNS 146; substance unchanged."),
    ("370", "143",   "Trafficking of person",
     "substantive_change",
     "Renumbered to BNS 143. Substantive changes: BNS expands definition to include exploitation for surrogacy and organ harvesting. Enhanced penalties for trafficking of children (minimum 14 years). Expanded victim-protective provisions."),
    ("370A","143",   "Exploitation of a trafficked person",
     "substantive_change",
     "Merged into BNS 143. Exploitation provisions consolidated and expanded."),
    ("371", "143",   "Habitual dealing in slaves",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("372", "143",   "Selling minor for purposes of prostitution, etc.",
     "renumbering_only",
     "Renumbered; now part of trafficking framework in BNS 143."),
    ("373", "143",   "Buying minor for purposes of prostitution, etc.",
     "renumbering_only",
     "Renumbered; now part of trafficking framework in BNS 143."),
    ("374", "144",   "Unlawful compulsory labour",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("375", "63",    "Rape",
     "substantive_change",
     "Renumbered to BNS 63. Substantive change: marital rape exception updated — 'wife under 15 years' changed to 'wife under 18 years', effectively aligning with POCSO and child marriage laws. Seven circumstances constituting rape retained."),
    ("376", "64",    "Punishment for rape",
     "renumbering_only",
     "Renumbered to BNS 64; minimum 10 years (up to life) for rape; minimum 20 years for rape of woman under 12 or 16 years. Enhanced sentences for public servants/police officers retained."),
    ("376A","66",    "Punishment for causing death or resulting in persistent vegetative state of victim",
     "renumbering_only",
     "Renumbered to BNS 66; death or imprisonment for life unchanged."),
    ("376AB","65",   "Punishment for rape on woman under twelve years of age",
     "renumbering_only",
     "Renumbered to BNS 65; minimum 20 years up to life + fine for medical expenses unchanged."),
    ("376B","67",    "Sexual intercourse by husband upon his wife during separation",
     "renumbering_only",
     "Renumbered to BNS 67; punishment (2 to 7 years) unchanged."),
    ("376C","68",    "Sexual intercourse by a person in authority",
     "renumbering_only",
     "Renumbered to BNS 68; substance unchanged."),
    ("376D","70",    "Gang rape",
     "renumbering_only",
     "Renumbered to BNS 70; minimum 20 years (life or death for victim under 18) unchanged."),
    ("376DA","71",   "Punishment for gang rape on woman under sixteen years of age",
     "renumbering_only",
     "Renumbered to BNS 71; life imprisonment + fine unchanged."),
    ("376DB","71",   "Punishment for gang rape on woman under twelve years of age",
     "renumbering_only",
     "Renumbered; life or death + fine unchanged."),
    ("376E","69",    "Punishment for repeat offenders",
     "renumbering_only",
     "Renumbered to BNS 69; life imprisonment or death for repeat rape offenders unchanged."),
    ("377", None,    "Unnatural offences",
     "deleted",
     "DELETED from BNS entirely. Follows Supreme Court ruling in Navtej Singh Johar v. Union of India (2018) which struck down IPC 377 as unconstitutional to the extent it criminalised consensual sexual acts between adults in private. Non-consensual acts are covered under other BNS sections."),

    # ── CHAPTER XVII  OFFENCES AGAINST PROPERTY (IPC 378-462) ─────────────────
    ("378", "303",   "Theft",
     "renumbering_only",
     "Renumbered to BNS 303; definition (dishonestly taking movable property out of possession without consent) unchanged."),
    ("379", "303",   "Punishment for theft",
     "renumbering_only",
     "Renumbered; punishment (up to 3 years, or fine, or both) merged into BNS 303."),
    ("380", "305",   "Theft in dwelling house, etc.",
     "renumbering_only",
     "Renumbered to BNS 305; punishment (up to 7 years + fine) unchanged."),
    ("381", "306",   "Theft by clerk or servant of property in possession of master",
     "renumbering_only",
     "Renumbered to BNS 306; punishment (up to 7 years + fine) unchanged."),
    ("382", "307",   "Theft after preparation made for causing death, hurt or restraint in order to the committing of the theft",
     "renumbering_only",
     "Renumbered to BNS 307; punishment (up to 10 years + fine) unchanged."),
    ("383", "308",   "Extortion",
     "renumbering_only",
     "Renumbered to BNS 308; definition of extortion unchanged."),
    ("384", "308(2)","Punishment for extortion",
     "renumbering_only",
     "Renumbered to BNS 308(2); punishment (up to 3 years, or fine, or both) unchanged."),
    ("385", "308",   "Putting person in fear of injury in order to commit extortion",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("386", "308",   "Extortion by putting a person in fear of death or grievous hurt",
     "renumbering_only",
     "Renumbered; punishment (up to 10 years + fine) unchanged."),
    ("387", "308",   "Putting person in fear of death or of grievous hurt, in order to commit extortion",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("388", "308",   "Extortion by threat of accusation of an offence punishable with death or imprisonment for life, etc.",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("389", "308",   "Putting person in fear of accusation of offence, in order to commit extortion",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("390", "309",   "Robbery",
     "renumbering_only",
     "Renumbered to BNS 309; definition of robbery unchanged."),
    ("391", "310",   "Dacoity",
     "renumbering_only",
     "Renumbered to BNS 310; five or more persons committing robbery is dacoity. Unchanged."),
    ("392", "309",   "Punishment for robbery",
     "renumbering_only",
     "Renumbered to BNS 309; punishment (up to 10 years + fine; 14 years for highway robbery) unchanged."),
    ("393", "309",   "Attempt to commit robbery",
     "renumbering_only",
     "Renumbered; punishment (up to 7 years + fine) unchanged."),
    ("394", "309",   "Voluntarily causing hurt in committing robbery",
     "renumbering_only",
     "Renumbered; punishment (life or up to 10 years + fine) unchanged."),
    ("395", "310",   "Punishment for dacoity",
     "renumbering_only",
     "Renumbered to BNS 310; punishment (rigorous imprisonment up to 10 years + fine) unchanged."),
    ("396", "310",   "Dacoity with murder",
     "renumbering_only",
     "Renumbered; death or life imprisonment unchanged."),
    ("397", "311",   "Robbery, or dacoity, with attempt to cause death or grievous hurt",
     "renumbering_only",
     "Renumbered to BNS 311; minimum 7-year sentence unchanged."),
    ("398", "311",   "Attempt to commit robbery or dacoity when armed with deadly weapon",
     "renumbering_only",
     "Renumbered; minimum 7 years unchanged."),
    ("399", "312",   "Making preparation to commit dacoity",
     "renumbering_only",
     "Renumbered to BNS 312; punishment (up to 10 years + fine) unchanged."),
    ("400", "312",   "Punishment for belonging to gang of dacoits",
     "renumbering_only",
     "Renumbered; life imprisonment or 10 years + fine unchanged."),
    ("401", "313",   "Punishment for belonging to gang of thieves",
     "renumbering_only",
     "Renumbered to BNS 313; punishment (up to 7 years + fine) unchanged."),
    ("402", "314",   "Assembling for purpose of committing dacoity",
     "renumbering_only",
     "Renumbered to BNS 314; punishment (up to 7 years + fine) unchanged."),
    ("403", "314",   "Dishonest misappropriation of property",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("404", "315",   "Dishonest misappropriation of property possessed by deceased person at the time of his death",
     "renumbering_only",
     "Renumbered to BNS 315; substance unchanged."),
    ("405", "316",   "Criminal breach of trust",
     "renumbering_only",
     "Renumbered to BNS 316; definition unchanged."),
    ("406", "316(2)","Punishment for criminal breach of trust",
     "renumbering_only",
     "Renumbered to BNS 316(2); punishment (up to 3 years, or fine, or both) unchanged."),
    ("407", "316",   "Criminal breach of trust by carrier, wharfinger, etc.",
     "renumbering_only",
     "Renumbered; punishment (up to 7 years + fine) unchanged."),
    ("408", "316",   "Criminal breach of trust by clerk or servant",
     "renumbering_only",
     "Renumbered; punishment (up to 7 years + fine) unchanged."),
    ("409", "316",   "Criminal breach of trust by public servant, or by banker, merchant or agent",
     "renumbering_only",
     "Renumbered; punishment (life or up to 10 years + fine) unchanged."),
    ("410", "317",   "Stolen property",
     "renumbering_only",
     "Renumbered to BNS 317; definition of stolen property unchanged."),
    ("411", "317",   "Dishonestly receiving stolen property",
     "renumbering_only",
     "Renumbered; punishment (up to 3 years, or fine, or both) unchanged."),
    ("412", "317",   "Dishonestly receiving property stolen in the commission of a dacoity",
     "renumbering_only",
     "Renumbered; punishment (life or up to 10 years + fine) unchanged."),
    ("413", "317",   "Habitually dealing in stolen property",
     "renumbering_only",
     "Renumbered; punishment (life or up to 10 years + fine) unchanged."),
    ("414", "317",   "Assisting in concealment of stolen property",
     "renumbering_only",
     "Renumbered; punishment (up to 3 years, or fine, or both) unchanged."),
    ("415", "318(1)","Cheating",
     "renumbering_only",
     "Renumbered to BNS 318(1); definition (fraudulent/dishonest inducement to deliver property or alter document) unchanged."),
    ("416", "318",   "Cheating by personation",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("417", "318",   "Punishment for cheating",
     "renumbering_only",
     "Renumbered; punishment (up to 1 year, or fine, or both) unchanged."),
    ("418", "318",   "Cheating with knowledge that wrongful loss may ensue to person whose interest offender is bound to protect",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("419", "319",   "Punishment for cheating by personation",
     "renumbering_only",
     "Renumbered to BNS 319; punishment (up to 3 years + fine) unchanged."),
    ("420", "318(4)","Cheating and dishonestly inducing delivery of property",
     "substantive_change",
     "IPC 420 (standalone section) merged into BNS 318(4). The 7-year maximum and fine are retained, but 420 is no longer a standalone section number. Prosecutors must cite BNS 318(4) instead of IPC 420."),
    ("421", "319",   "Dishonest or fraudulent removal or concealment of property to prevent distribution among creditors",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("422", "319",   "Dishonestly or fraudulently preventing debt being available for creditors",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("423", "320",   "Dishonest or fraudulent execution of deed of transfer containing false statement of consideration",
     "renumbering_only",
     "Renumbered to BNS 320; substance unchanged."),
    ("424", "321",   "Dishonest or fraudulent removal or concealment of property",
     "renumbering_only",
     "Renumbered to BNS 321; substance unchanged."),
    ("425", "324",   "Mischief",
     "renumbering_only",
     "Renumbered to BNS 324; definition (intentional wrongful loss/damage to property) unchanged."),
    ("426", "324",   "Punishment for mischief",
     "renumbering_only",
     "Renumbered; punishment (up to 3 months, or fine, or both) unchanged."),
    ("427", "324",   "Mischief causing damage to the amount of fifty rupees",
     "renumbering_only",
     "Renumbered; punishment (up to 2 years, or fine, or both) unchanged."),
    ("428", "325",   "Mischief by killing or maiming animal of the value of ten rupees",
     "renumbering_only",
     "Renumbered to BNS 325; substance unchanged."),
    ("429", "325",   "Mischief by killing or maiming cattle, etc., of any value or any animal of the value of fifty rupees",
     "renumbering_only",
     "Renumbered; punishment (up to 5 years + fine) unchanged."),
    ("430", "326",   "Mischief by injury to works of irrigation or by wrongfully diverting water",
     "renumbering_only",
     "Renumbered to BNS 326; substance unchanged."),
    ("431", "326",   "Mischief by injury to public road, bridge, river or channel",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("432", "326",   "Mischief by causing inundation or obstruction to public drainage attended with damage",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("433", "326",   "Mischief by destroying, moving or rendering less useful a light-house or sea-mark",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("434", "326",   "Mischief by destroying or moving, etc., a land-mark fixed by public authority",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("435", "326",   "Mischief by fire or explosive substance with intent to cause damage to amount of one hundred rupees",
     "renumbering_only",
     "Renumbered; punishment (up to 7 years + fine) unchanged."),
    ("436", "326",   "Mischief by fire or explosive substance with intent to destroy house, etc.",
     "renumbering_only",
     "Renumbered; life or up to 10 years + fine unchanged."),
    ("437", "326",   "Mischief with intent to destroy or make unsafe a decked vessel or one of twenty tons burden",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("438", "327",   "Punishment for the mischief described in section 437 committed by fire or explosive substance",
     "renumbering_only",
     "Renumbered to BNS 327; substance unchanged."),
    ("439", "326",   "Mischief by unlawfully diverting water of a river or of a public spring from its natural bed",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("440", "328",   "Mischief committed after preparation made for causing death or hurt",
     "renumbering_only",
     "Renumbered to BNS 328; punishment (life or up to 5 years + fine) unchanged."),
    ("441", "329",   "Criminal trespass",
     "substantive_change",
     "Renumbered to BNS 329. Substantive change: BNS adds digital/electronic means to the definition — unauthorised entry into computer systems or digital networks is now expressly covered."),
    ("442", "330",   "House-trespass",
     "renumbering_only",
     "Renumbered to BNS 330; definition of house-trespass unchanged."),
    ("443", "331",   "Lurking house-trespass",
     "renumbering_only",
     "Renumbered to BNS 331; substance unchanged."),
    ("444", "331",   "Lurking house-trespass by night",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("445", "332",   "House-breaking",
     "renumbering_only",
     "Renumbered to BNS 332; six modes of house-breaking unchanged."),
    ("446", "332",   "House-breaking by night",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("447", "329(1)","Punishment for criminal trespass",
     "substantive_change",
     "IPC 447 merged into BNS 329(1). Punishment (up to 3 months, or fine up to Rs 5,000) unchanged. Note: cite BNS 329(1), not IPC 447."),
    ("448", "330",   "Punishment for house-trespass",
     "renumbering_only",
     "Renumbered to BNS 330; punishment (up to 1 year, or fine up to Rs 5,000) unchanged."),
    ("449", "333",   "House-trespass in order to commit offence punishable with death",
     "renumbering_only",
     "Renumbered to BNS 333; life or up to 10 years + fine unchanged."),
    ("450", "334",   "House-trespass in order to commit offence punishable with imprisonment for life",
     "renumbering_only",
     "Renumbered to BNS 334; substance unchanged."),
    ("451", "331",   "House-trespass in order to commit offence punishable with imprisonment",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("452", "331",   "House-trespass after preparation for hurt, assault or wrongful restraint",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("453", "331",   "Punishment for lurking house-trespass or house-breaking",
     "renumbering_only",
     "Renumbered; punishment (up to 2 years + fine) unchanged."),
    ("454", "331",   "Lurking house-trespass or house-breaking in order to commit offence punishable with imprisonment",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("455", "331",   "Lurking house-trespass or house-breaking after preparation for hurt, assault or wrongful restraint",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("456", "332",   "Punishment for lurking house-trespass or house-breaking by night",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("457", "332",   "Lurking house-trespass or house-breaking by night in order to commit offence punishable with imprisonment",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("458", "332",   "Lurking house-trespass or house-breaking by night after preparation for hurt, assault or wrongful restraint",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("459", "333",   "Grievous hurt caused whilst committing lurking house-trespass or house-breaking",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("460", "333",   "All persons jointly concerned in lurking house-trespass or house-breaking by night punishable where death or grievous hurt caused by one of them",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("461", "334",   "Dishonestly breaking open receptacle containing property",
     "renumbering_only",
     "Renumbered to BNS 334; substance unchanged."),
    ("462", "334",   "Punishment for same offence when committed by person entrusted with custody",
     "renumbering_only",
     "Renumbered; substance unchanged."),

    # ── CHAPTER XVIII  DOCUMENTS AND PROPERTY MARKS (IPC 463-477A) ────────────
    ("463", "336",   "Forgery",
     "renumbering_only",
     "Renumbered to BNS 336; definition (making false document/electronic record with intent to cause damage) unchanged."),
    ("464", "337",   "Making a false document",
     "renumbering_only",
     "Renumbered to BNS 337; definition includes electronic records. Unchanged."),
    ("465", "338",   "Punishment for forgery",
     "renumbering_only",
     "Renumbered to BNS 338; punishment (up to 2 years, or fine, or both) unchanged."),
    ("466", "338",   "Forgery of record of Court or of public register, etc.",
     "renumbering_only",
     "Renumbered; punishment (up to 7 years + fine) unchanged."),
    ("467", "338",   "Forgery of valuable security, will, etc.",
     "renumbering_only",
     "Renumbered; punishment (life or up to 10 years + fine) unchanged."),
    ("468", "339",   "Forgery for purpose of cheating",
     "renumbering_only",
     "Renumbered to BNS 339; punishment (up to 7 years + fine) unchanged."),
    ("469", "340",   "Forgery for purpose of harming reputation",
     "renumbering_only",
     "Renumbered to BNS 340; punishment (up to 3 years + fine) unchanged."),
    ("470", "341",   "Forged document",
     "renumbering_only",
     "Renumbered to BNS 341; definition unchanged."),
    ("471", "342",   "Using as genuine a forged document",
     "renumbering_only",
     "Renumbered to BNS 342; punishment same as for forgery of that document."),
    ("472", "343",   "Making or possessing counterfeit seal, etc., with intent to commit forgery punishable under section 467",
     "renumbering_only",
     "Renumbered to BNS 343; substance unchanged."),
    ("473", "344",   "Making or possessing counterfeit seal, etc., with intent to commit forgery punishable otherwise",
     "renumbering_only",
     "Renumbered to BNS 344; substance unchanged."),
    ("474", "345",   "Having possession of document described in section 466 or 467, knowing it to be forged and intending to use it as genuine",
     "renumbering_only",
     "Renumbered to BNS 345; substance unchanged."),
    ("475", "346",   "Counterfeiting device or mark used for authenticating documents described in section 467, or possessing counterfeit marked material",
     "renumbering_only",
     "Renumbered to BNS 346; substance unchanged."),
    ("476", "347",   "Counterfeiting device or mark used for authenticating documents other than those described in section 467, or possessing counterfeit marked material",
     "renumbering_only",
     "Renumbered to BNS 347; substance unchanged."),
    ("477", "348",   "Fraudulent cancellation, destruction, etc., of will, authority to adopt, or valuable security",
     "renumbering_only",
     "Renumbered to BNS 348; substance unchanged."),
    ("477A","349",   "Falsification of accounts",
     "renumbering_only",
     "Renumbered to BNS 349; substance unchanged."),
    ("478", "350",   "Trade mark",
     "renumbering_only",
     "Renumbered to BNS 350; substance unchanged."),
    ("479", "350",   "Property mark",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("480", "350",   "Using a false trade mark",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("481", "350",   "Using a false property mark",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("482", "350",   "Punishment for using a false trade mark or property mark",
     "renumbering_only",
     "Renumbered; punishment (up to 1 year, or fine, or both) unchanged."),
    ("483", "350",   "Counterfeiting a trade mark or property mark used by another",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("484", "350",   "Counterfeiting a mark used by a public servant",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("485", "350",   "Making or possession of any instrument for counterfeiting a trade mark or property mark",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("486", "350",   "Selling goods marked with a counterfeit trade mark or property mark",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("487", "350",   "Making a false mark upon any receptacle containing goods",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("488", "350",   "Punishment for making use of any such false mark",
     "renumbering_only",
     "Renumbered; punishment (up to 1 year, or fine, or both) unchanged."),
    ("489", "350",   "Tampering with property mark with intent to cause injury",
     "renumbering_only",
     "Renumbered; substance unchanged."),
    ("489A","178",   "Counterfeiting currency-notes or bank-notes",
     "renumbering_only",
     "Renumbered to BNS 178; life imprisonment, or up to 10 years + fine unchanged."),
    ("489B","179",   "Using as genuine, forged or counterfeit currency-notes or bank-notes",
     "renumbering_only",
     "Renumbered to BNS 179; punishment (life or up to 10 years + fine) unchanged."),
    ("489C","180",   "Possession of forged or counterfeit currency-notes or bank-notes",
     "renumbering_only",
     "Renumbered to BNS 180; punishment (up to 7 years + fine) unchanged."),
    ("489D","181",   "Making or possessing instruments or materials for forging or counterfeiting currency-notes or bank-notes",
     "renumbering_only",
     "Renumbered to BNS 181; life or up to 10 years + fine unchanged."),
    ("489E","182",   "Making or using documents resembling currency-notes or bank-notes",
     "renumbering_only",
     "Renumbered to BNS 182; punishment (up to 1 year, or fine, or both) unchanged."),

    # ── CHAPTER XIX  CRIMINAL BREACH OF CONTRACTS (IPC 490-492) ──────────────
    ("490", "357",   "Breach of contract to attend on and supply wants of helpless person",
     "renumbering_only",
     "Renumbered to BNS 357; punishment (up to 3 months, or fine, or both) unchanged."),
    ("491", "358",   "Breach of contract to attend on and supply wants of helpless person",
     "renumbering_only",
     "Renumbered to BNS 358; substance unchanged."),
    ("492", "359",   "Breach of contract to serve at distant place to which person is conveyed",
     "renumbering_only",
     "Renumbered to BNS 359; substance unchanged."),

    # ── CHAPTER XX  OFFENCES RELATING TO MARRIAGE (IPC 493-498) ─────────────
    ("493", "81",    "Cohabitation caused by a man deceitfully inducing a belief of lawful marriage",
     "renumbering_only",
     "Renumbered to BNS 81; punishment (up to 10 years + fine) unchanged."),
    ("494", "82",    "Marrying again during lifetime of husband or wife",
     "renumbering_only",
     "Renumbered to BNS 82; bigamy punishment (up to 7 years + fine) unchanged."),
    ("495", "83",    "Same offence with concealment of former marriage from person with whom subsequent marriage is contracted",
     "renumbering_only",
     "Renumbered to BNS 83; substance unchanged."),
    ("496", "84",    "Marriage ceremony fraudulently gone through without lawful marriage",
     "renumbering_only",
     "Renumbered to BNS 84; punishment (up to 7 years + fine) unchanged."),
    ("497", None,    "Adultery",
     "deleted",
     "DELETED from BNS. The Supreme Court in Joseph Shine v. Union of India (2018) struck down IPC 497 as unconstitutional — it treated women as property of their husbands. Adultery is no longer a criminal offence."),
    ("498", "85",    "Enticing or taking away or detaining with criminal intent a married woman",
     "renumbering_only",
     "Renumbered to BNS 85; punishment (up to 2 years, or fine, or both) unchanged."),

    # ── CHAPTER XX-A  CRUELTY BY HUSBAND OR HIS RELATIVES (IPC 498A) ─────────
    ("498A","85",    "Husband or relative of husband of a woman subjecting her to cruelty",
     "renumbering_only",
     "Renumbered to BNS 85; definition of cruelty (driving to suicide or causing grievous hurt for dowry) and 3-year punishment unchanged. Supreme Court safeguards against misuse (Rajesh Sharma 2017) continue to apply."),

    # ── CHAPTER XXI  DEFAMATION (IPC 499-502) ────────────────────────────────
    ("499", "356(1)","Defamation",
     "renumbering_only",
     "Renumbered to BNS 356(1); definition (imputation by speech, writing, signs, visible representations harming reputation) and 10 exceptions unchanged."),
    ("500", "356(2)","Punishment for defamation",
     "renumbering_only",
     "Renumbered to BNS 356(2); punishment (up to 2 years simple imprisonment, or fine, or both) unchanged."),
    ("501", "357",   "Printing or engraving matter known to be defamatory",
     "renumbering_only",
     "Renumbered to BNS 357; substance unchanged."),
    ("502", "358",   "Sale of printed or engraved substance containing defamatory matter",
     "renumbering_only",
     "Renumbered to BNS 358; substance unchanged."),

    # ── CHAPTER XXII  CRIMINAL INTIMIDATION, INSULT AND ANNOYANCE (IPC 503-510)
    ("503", "351(1)","Criminal intimidation",
     "substantive_change",
     "Renumbered to BNS 351(1). Substantive change: BNS expressly adds threats communicated through digital or electronic means — online threats, WhatsApp/email threats to harm person or reputation are now explicitly covered."),
    ("504", "352",   "Intentional insult with intent to provoke breach of the peace",
     "renumbering_only",
     "Renumbered to BNS 352; punishment (up to 2 years, or fine, or both) unchanged."),
    ("505", "353",   "Statements conducing to public mischief",
     "substantive_change",
     "Renumbered to BNS 353. BNS expands to include statements spread through electronic media and social networking platforms. Punishment (up to 3 years; up to 6 years if relating to enemy's power) unchanged."),
    ("506", "351",   "Punishment for criminal intimidation",
     "renumbering_only",
     "Renumbered to BNS 351; simple intimidation up to 2 years; threat of death/grievous hurt up to 7 years. Unchanged."),
    ("507", "354",   "Criminal intimidation by an anonymous communication",
     "renumbering_only",
     "Renumbered to BNS 354; punishment (up to 2 years in addition to punishment under 351) unchanged."),
    ("508", "355",   "Act caused by inducing person to believe that he will be rendered an object of the Divine displeasure",
     "renumbering_only",
     "Renumbered to BNS 355; substance unchanged."),
    ("509", "79",    "Word, gesture or act intended to insult the modesty of a woman",
     "substantive_change",
     "Renumbered to BNS 79. Substantive change: BNS explicitly includes digital communications — obscene electronic messages, unsolicited sexually explicit images (sexting), online harassment of women. Punishment enhanced from 1 year to 3 years."),
    ("510", "356",   "Misconduct in public by a drunken person",
     "renumbering_only",
     "Renumbered to BNS 356; substance unchanged."),

    # ── CHAPTER XXIII  ATTEMPTS TO COMMIT OFFENCES (IPC 511) ─────────────────
    ("511", "62",    "Punishment for attempting to commit offences punishable with imprisonment for life or other imprisonment",
     "substantive_change",
     "Renumbered to BNS 62. Substantive change: The general 'attempt' provision is now BNS 62. BNS also introduces specific attempt provisions within individual offence sections (e.g., BNS 109 for attempt to murder). The general fallback principle (up to half the maximum punishment for the completed offence) is retained."),
]


def build_entry(row: tuple) -> dict:
    ipc, bns, title, ctype, note = row
    return {
        "ipc_section":  ipc,
        "bns_section":  bns,
        "offence":      title,
        "change_type":  ctype,
        "what_changed": note,
        "verified":     False,
    }


def main():
    data = json.loads(FILE.read_text(encoding="utf-8"))

    complete = [build_entry(r) for r in ENTRIES]

    data["ipc_complete_mapping"] = complete
    # Update metadata
    data.setdefault("metadata", {})
    data["metadata"]["ipc_complete_mapping_count"] = len(complete)
    data["metadata"]["ipc_complete_mapping_note"]  = (
        "All 511 IPC sections mapped. "
        "All entries verified=false — requires advocate sign-off before use in filings."
    )

    FILE.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Done — wrote {len(complete)} IPC entries to ipc_complete_mapping.")

    # Sanity check
    deleted   = sum(1 for e in complete if e["bns_section"] is None)
    merged    = sum(1 for e in complete if e["change_type"] == "merged")
    subst     = sum(1 for e in complete if e["change_type"] == "substantive_change")
    print(f"  substantive_change: {subst}")
    print(f"  merged into definitions: {merged}")
    print(f"  deleted: {deleted}")
    print(f"  renumbered: {len(complete) - deleted - merged - subst}")


if __name__ == "__main__":
    main()
