/**
 * courtData.ts — eCourts state / district / court-complex reference data.
 * Source: eCourts India national portal (ecourts.gov.in) establishment lists.
 */

export interface StateUT  { code: string; name: string }
export interface District { code: string; name: string }
export interface Complex  { code: string; name: string }

// ── All 36 States & UTs  (code = eCourts numeric state_code) ─────────────────
export const STATES_UTS: StateUT[] = [
  { code: '30', name: 'Andaman & Nicobar Islands' },
  { code: '1',  name: 'Andhra Pradesh' },
  { code: '2',  name: 'Arunachal Pradesh' },
  { code: '3',  name: 'Assam' },
  { code: '4',  name: 'Bihar' },
  { code: '31', name: 'Chandigarh' },
  { code: '5',  name: 'Chhattisgarh' },
  { code: '32', name: 'Dadra & Nagar Haveli and Daman & Diu' },
  { code: '33', name: 'Delhi' },
  { code: '6',  name: 'Goa' },
  { code: '7',  name: 'Gujarat' },
  { code: '8',  name: 'Haryana' },
  { code: '9',  name: 'Himachal Pradesh' },
  { code: '10', name: 'Jammu & Kashmir' },
  { code: '11', name: 'Jharkhand' },
  { code: '12', name: 'Karnataka' },
  { code: '13', name: 'Kerala' },
  { code: '34', name: 'Ladakh' },
  { code: '35', name: 'Lakshadweep' },
  { code: '14', name: 'Madhya Pradesh' },
  { code: '15', name: 'Maharashtra' },
  { code: '16', name: 'Manipur' },
  { code: '17', name: 'Meghalaya' },
  { code: '18', name: 'Mizoram' },
  { code: '19', name: 'Nagaland' },
  { code: '20', name: 'Odisha' },
  { code: '36', name: 'Puducherry' },
  { code: '21', name: 'Punjab' },
  { code: '22', name: 'Rajasthan' },
  { code: '23', name: 'Sikkim' },
  { code: '24', name: 'Tamil Nadu' },
  { code: '25', name: 'Telangana' },
  { code: '26', name: 'Tripura' },
  { code: '27', name: 'Uttar Pradesh' },
  { code: '28', name: 'Uttarakhand' },
  { code: '29', name: 'West Bengal' },
];

// ── Districts (keyed by state code) ──────────────────────────────────────────
export const DISTRICTS: Record<string, District[]> = {
  '33': [ // Delhi
    { code: '01', name: 'Central Delhi' },
    { code: '02', name: 'East Delhi' },
    { code: '03', name: 'New Delhi' },
    { code: '04', name: 'North Delhi' },
    { code: '05', name: 'North East Delhi' },
    { code: '06', name: 'North West Delhi' },
    { code: '07', name: 'Shahdara' },
    { code: '08', name: 'South Delhi' },
    { code: '09', name: 'South East Delhi' },
    { code: '10', name: 'South West Delhi' },
    { code: '11', name: 'West Delhi' },
  ],
  '15': [ // Maharashtra
    { code: '01', name: 'Mumbai City' },
    { code: '02', name: 'Mumbai Suburban' },
    { code: '03', name: 'Thane' },
    { code: '04', name: 'Pune' },
    { code: '05', name: 'Nashik' },
    { code: '06', name: 'Aurangabad (Chhatrapati Sambhajinagar)' },
    { code: '07', name: 'Nagpur' },
    { code: '08', name: 'Solapur' },
    { code: '09', name: 'Kolhapur' },
    { code: '10', name: 'Satara' },
    { code: '11', name: 'Sangli' },
    { code: '12', name: 'Raigad' },
    { code: '13', name: 'Ratnagiri' },
    { code: '14', name: 'Sindhudurg' },
    { code: '15', name: 'Ahmednagar' },
    { code: '16', name: 'Jalgaon' },
    { code: '17', name: 'Dhule' },
    { code: '18', name: 'Nandurbar' },
    { code: '19', name: 'Nanded' },
    { code: '20', name: 'Latur' },
    { code: '21', name: 'Osmanabad (Dharashiv)' },
    { code: '22', name: 'Beed' },
    { code: '23', name: 'Parbhani' },
    { code: '24', name: 'Hingoli' },
    { code: '25', name: 'Jalna' },
    { code: '26', name: 'Washim' },
    { code: '27', name: 'Akola' },
    { code: '28', name: 'Amravati' },
    { code: '29', name: 'Wardha' },
    { code: '30', name: 'Yavatmal' },
    { code: '31', name: 'Buldhana' },
    { code: '32', name: 'Chandrapur' },
    { code: '33', name: 'Gadchiroli' },
    { code: '34', name: 'Gondia' },
    { code: '35', name: 'Bhandara' },
  ],
  '12': [ // Karnataka
    { code: '01', name: 'Bangalore Urban' },
    { code: '02', name: 'Bangalore Rural' },
    { code: '03', name: 'Mysuru' },
    { code: '04', name: 'Tumkur' },
    { code: '05', name: 'Mandya' },
    { code: '06', name: 'Hassan' },
    { code: '07', name: 'Kodagu' },
    { code: '08', name: 'Dakshina Kannada' },
    { code: '09', name: 'Udupi' },
    { code: '10', name: 'Shimoga' },
    { code: '11', name: 'Chickmagalur' },
    { code: '12', name: 'Davanagere' },
    { code: '13', name: 'Chitradurga' },
    { code: '14', name: 'Bellary' },
    { code: '15', name: 'Raichur' },
    { code: '16', name: 'Koppal' },
    { code: '17', name: 'Kalaburagi' },
    { code: '18', name: 'Bidar' },
    { code: '19', name: 'Yadgiri' },
    { code: '20', name: 'Vijayapura' },
    { code: '21', name: 'Bagalkot' },
    { code: '22', name: 'Dharwad' },
    { code: '23', name: 'Gadag' },
    { code: '24', name: 'Haveri' },
    { code: '25', name: 'Uttara Kannada' },
    { code: '26', name: 'Belagavi' },
    { code: '27', name: 'Chikkaballapur' },
    { code: '28', name: 'Kolar' },
    { code: '29', name: 'Ramanagara' },
    { code: '30', name: 'Chamarajanagara' },
    { code: '31', name: 'Vijayanagara' },
  ],
  '24': [ // Tamil Nadu
    { code: '01', name: 'Chennai' },
    { code: '02', name: 'Kancheepuram' },
    { code: '03', name: 'Tiruvallur' },
    { code: '04', name: 'Vellore' },
    { code: '05', name: 'Tiruvannamalai' },
    { code: '06', name: 'Villupuram' },
    { code: '07', name: 'Salem' },
    { code: '08', name: 'Namakkal' },
    { code: '09', name: 'Erode' },
    { code: '10', name: 'Coimbatore' },
    { code: '11', name: 'The Nilgiris' },
    { code: '12', name: 'Dindigul' },
    { code: '13', name: 'Karur' },
    { code: '14', name: 'Tiruchirappalli' },
    { code: '15', name: 'Perambalur' },
    { code: '16', name: 'Ariyalur' },
    { code: '17', name: 'Cuddalore' },
    { code: '18', name: 'Nagapattinam' },
    { code: '19', name: 'Thanjavur' },
    { code: '20', name: 'Tiruvarur' },
    { code: '21', name: 'Pudukkottai' },
    { code: '22', name: 'Sivaganga' },
    { code: '23', name: 'Madurai' },
    { code: '24', name: 'Virudhunagar' },
    { code: '25', name: 'Ramanathapuram' },
    { code: '26', name: 'Thoothukudi' },
    { code: '27', name: 'Tirunelveli' },
    { code: '28', name: 'Kanyakumari' },
    { code: '29', name: 'Krishnagiri' },
    { code: '30', name: 'Dharmapuri' },
    { code: '31', name: 'Tenkasi' },
    { code: '32', name: 'Kallakurichi' },
    { code: '33', name: 'Ranipet' },
    { code: '34', name: 'Chengalpattu' },
    { code: '35', name: 'Mayiladuthurai' },
    { code: '36', name: 'Tirupathur' },
    { code: '37', name: 'Tiruppur' },
  ],
  '27': [ // Uttar Pradesh
    { code: '01', name: 'Agra' }, { code: '02', name: 'Aligarh' },
    { code: '03', name: 'Allahabad (Prayagraj)' }, { code: '04', name: 'Ambedkar Nagar' },
    { code: '05', name: 'Amethi' }, { code: '06', name: 'Amroha' },
    { code: '07', name: 'Auraiya' }, { code: '08', name: 'Azamgarh' },
    { code: '09', name: 'Baghpat' }, { code: '10', name: 'Bahraich' },
    { code: '11', name: 'Ballia' }, { code: '12', name: 'Balrampur' },
    { code: '13', name: 'Banda' }, { code: '14', name: 'Bara Banki' },
    { code: '15', name: 'Bareilly' }, { code: '16', name: 'Basti' },
    { code: '17', name: 'Bijnor' }, { code: '18', name: 'Budaun' },
    { code: '19', name: 'Bulandshahr' }, { code: '20', name: 'Chandauli' },
    { code: '21', name: 'Chitrakoot' }, { code: '22', name: 'Deoria' },
    { code: '23', name: 'Etah' }, { code: '24', name: 'Etawah' },
    { code: '25', name: 'Faizabad (Ayodhya)' }, { code: '26', name: 'Farrukhabad' },
    { code: '27', name: 'Fatehpur' }, { code: '28', name: 'Firozabad' },
    { code: '29', name: 'Gautam Buddha Nagar (Noida)' }, { code: '30', name: 'Ghaziabad' },
    { code: '31', name: 'Ghazipur' }, { code: '32', name: 'Gonda' },
    { code: '33', name: 'Gorakhpur' }, { code: '34', name: 'Hamirpur' },
    { code: '35', name: 'Hapur' }, { code: '36', name: 'Hardoi' },
    { code: '37', name: 'Hathras' }, { code: '38', name: 'Jalaun' },
    { code: '39', name: 'Jaunpur' }, { code: '40', name: 'Jhansi' },
    { code: '41', name: 'Kannauj' }, { code: '42', name: 'Kanpur Dehat' },
    { code: '43', name: 'Kanpur Nagar' }, { code: '44', name: 'Kasganj' },
    { code: '45', name: 'Kaushambi' }, { code: '46', name: 'Kushinagar' },
    { code: '47', name: 'Lakhimpur Kheri' }, { code: '48', name: 'Lalitpur' },
    { code: '49', name: 'Lucknow' }, { code: '50', name: 'Maharajganj' },
    { code: '51', name: 'Mahoba' }, { code: '52', name: 'Mainpuri' },
    { code: '53', name: 'Mathura' }, { code: '54', name: 'Mau' },
    { code: '55', name: 'Meerut' }, { code: '56', name: 'Mirzapur' },
    { code: '57', name: 'Moradabad' }, { code: '58', name: 'Muzaffarnagar' },
    { code: '59', name: 'Pilibhit' }, { code: '60', name: 'Pratapgarh' },
    { code: '61', name: 'Raebareli' }, { code: '62', name: 'Rampur' },
    { code: '63', name: 'Saharanpur' }, { code: '64', name: 'Sambhal' },
    { code: '65', name: 'Sant Kabir Nagar' }, { code: '66', name: 'Shahjahanpur' },
    { code: '67', name: 'Shamli' }, { code: '68', name: 'Shravasti' },
    { code: '69', name: 'Siddharthnagar' }, { code: '70', name: 'Sitapur' },
    { code: '71', name: 'Sonbhadra' }, { code: '72', name: 'Sultanpur' },
    { code: '73', name: 'Unnao' }, { code: '74', name: 'Varanasi' },
    { code: '75', name: 'Hardoi' },
  ],
  '7': [ // Gujarat
    { code: '01', name: 'Ahmedabad' }, { code: '02', name: 'Amreli' },
    { code: '03', name: 'Anand' }, { code: '04', name: 'Aravalli' },
    { code: '05', name: 'Banaskantha' }, { code: '06', name: 'Bharuch' },
    { code: '07', name: 'Bhavnagar' }, { code: '08', name: 'Botad' },
    { code: '09', name: 'Chhota Udaipur' }, { code: '10', name: 'Dahod' },
    { code: '11', name: 'Dang' }, { code: '12', name: 'Devbhoomi Dwarka' },
    { code: '13', name: 'Gandhinagar' }, { code: '14', name: 'Gir Somnath' },
    { code: '15', name: 'Jamnagar' }, { code: '16', name: 'Junagadh' },
    { code: '17', name: 'Kheda' }, { code: '18', name: 'Kutch' },
    { code: '19', name: 'Mahisagar' }, { code: '20', name: 'Mehsana' },
    { code: '21', name: 'Morbi' }, { code: '22', name: 'Narmada' },
    { code: '23', name: 'Navsari' }, { code: '24', name: 'Panchmahal' },
    { code: '25', name: 'Patan' }, { code: '26', name: 'Porbandar' },
    { code: '27', name: 'Rajkot' }, { code: '28', name: 'Sabarkantha' },
    { code: '29', name: 'Surat' }, { code: '30', name: 'Surendranagar' },
    { code: '31', name: 'Tapi' }, { code: '32', name: 'Vadodara' },
    { code: '33', name: 'Valsad' },
  ],
  '22': [ // Rajasthan
    { code: '01', name: 'Ajmer' }, { code: '02', name: 'Alwar' },
    { code: '03', name: 'Banswara' }, { code: '04', name: 'Baran' },
    { code: '05', name: 'Barmer' }, { code: '06', name: 'Bharatpur' },
    { code: '07', name: 'Bhilwara' }, { code: '08', name: 'Bikaner' },
    { code: '09', name: 'Bundi' }, { code: '10', name: 'Chittorgarh' },
    { code: '11', name: 'Churu' }, { code: '12', name: 'Dausa' },
    { code: '13', name: 'Dholpur' }, { code: '14', name: 'Dungarpur' },
    { code: '15', name: 'Hanumangarh' }, { code: '16', name: 'Jaipur' },
    { code: '17', name: 'Jaisalmer' }, { code: '18', name: 'Jalore' },
    { code: '19', name: 'Jhalawar' }, { code: '20', name: 'Jhunjhunu' },
    { code: '21', name: 'Jodhpur' }, { code: '22', name: 'Karauli' },
    { code: '23', name: 'Kota' }, { code: '24', name: 'Nagaur' },
    { code: '25', name: 'Pali' }, { code: '26', name: 'Pratapgarh' },
    { code: '27', name: 'Rajsamand' }, { code: '28', name: 'Sawai Madhopur' },
    { code: '29', name: 'Sikar' }, { code: '30', name: 'Sirohi' },
    { code: '31', name: 'Sri Ganganagar' }, { code: '32', name: 'Tonk' },
    { code: '33', name: 'Udaipur' },
  ],
  '29': [ // West Bengal
    { code: '01', name: 'Kolkata' }, { code: '02', name: 'Howrah' },
    { code: '03', name: 'Hooghly' }, { code: '04', name: 'North 24 Parganas' },
    { code: '05', name: 'South 24 Parganas' }, { code: '06', name: 'Nadia' },
    { code: '07', name: 'Murshidabad' }, { code: '08', name: 'Burdwan (Purba)' },
    { code: '09', name: 'Burdwan (Paschim)' }, { code: '10', name: 'Birbhum' },
    { code: '11', name: 'Bankura' }, { code: '12', name: 'Purulia' },
    { code: '13', name: 'Jhargram' }, { code: '14', name: 'Medinipur (Paschim)' },
    { code: '15', name: 'Medinipur (Purba)' }, { code: '16', name: 'North Dinajpur' },
    { code: '17', name: 'South Dinajpur' }, { code: '18', name: 'Malda' },
    { code: '19', name: 'Jalpaiguri' }, { code: '20', name: 'Darjeeling' },
    { code: '21', name: 'Cooch Behar' }, { code: '22', name: 'Alipurduar' },
    { code: '23', name: 'Kalimpong' },
  ],
  '25': [ // Telangana
    { code: '01', name: 'Hyderabad' }, { code: '02', name: 'Rangareddy' },
    { code: '03', name: 'Medchal-Malkajgiri' }, { code: '04', name: 'Warangal Urban' },
    { code: '05', name: 'Warangal Rural' }, { code: '06', name: 'Karimnagar' },
    { code: '07', name: 'Nizamabad' }, { code: '08', name: 'Nalgonda' },
    { code: '09', name: 'Mahbubnagar' }, { code: '10', name: 'Khammam' },
    { code: '11', name: 'Adilabad' }, { code: '12', name: 'Nirmal' },
    { code: '13', name: 'Mancherial' }, { code: '14', name: 'Komaram Bheem' },
    { code: '15', name: 'Peddapalli' }, { code: '16', name: 'Jagtial' },
    { code: '17', name: 'Rajanna Sircilla' }, { code: '18', name: 'Bhadradri Kothagudem' },
    { code: '19', name: 'Jayashankar Bhupalpally' }, { code: '20', name: 'Mulugu' },
    { code: '21', name: 'Suryapet' }, { code: '22', name: 'Yadadri Bhuvanagiri' },
    { code: '23', name: 'Vikarabad' }, { code: '24', name: 'Sangareddy' },
    { code: '25', name: 'Medak' }, { code: '26', name: 'Siddipet' },
    { code: '27', name: 'Kamareddy' }, { code: '28', name: 'Jangaon' },
    { code: '29', name: 'Mahabubabad' }, { code: '30', name: 'Nagarkurnool' },
    { code: '31', name: 'Wanaparthy' }, { code: '32', name: 'Gadwal' },
    { code: '33', name: 'Mahabubnagar' },
  ],
  '1': [ // Andhra Pradesh
    { code: '01', name: 'Srikakulam' }, { code: '02', name: 'Vizianagaram' },
    { code: '03', name: 'Visakhapatnam' }, { code: '04', name: 'East Godavari' },
    { code: '05', name: 'West Godavari' }, { code: '06', name: 'Krishna' },
    { code: '07', name: 'Guntur' }, { code: '08', name: 'Prakasam' },
    { code: '09', name: 'Nellore' }, { code: '10', name: 'Kurnool' },
    { code: '11', name: 'Kadapa' }, { code: '12', name: 'Anantapur' },
    { code: '13', name: 'Chittoor' }, { code: '14', name: 'Eluru' },
    { code: '15', name: 'Anakapalli' }, { code: '16', name: 'Bapatla' },
    { code: '17', name: 'Nandyal' }, { code: '18', name: 'Palnadu' },
    { code: '19', name: 'Tirupati' }, { code: '20', name: 'Sri Sathya Sai' },
    { code: '21', name: 'Alluri Sitharama Raju' }, { code: '22', name: 'Parvathipuram Manyam' },
    { code: '23', name: 'Kakinada' }, { code: '24', name: 'Konaseema' },
    { code: '25', name: 'NTR (Vijayawada)' }, { code: '26', name: 'Sri Balaji' },
  ],
  '13': [ // Kerala
    { code: '01', name: 'Thiruvananthapuram' }, { code: '02', name: 'Kollam' },
    { code: '03', name: 'Pathanamthitta' }, { code: '04', name: 'Alappuzha' },
    { code: '05', name: 'Kottayam' }, { code: '06', name: 'Idukki' },
    { code: '07', name: 'Ernakulam' }, { code: '08', name: 'Thrissur' },
    { code: '09', name: 'Palakkad' }, { code: '10', name: 'Malappuram' },
    { code: '11', name: 'Kozhikode' }, { code: '12', name: 'Wayanad' },
    { code: '13', name: 'Kannur' }, { code: '14', name: 'Kasaragod' },
  ],
  '8': [ // Haryana
    { code: '01', name: 'Ambala' }, { code: '02', name: 'Bhiwani' },
    { code: '03', name: 'Charkhi Dadri' }, { code: '04', name: 'Faridabad' },
    { code: '05', name: 'Fatehabad' }, { code: '06', name: 'Gurugram' },
    { code: '07', name: 'Hisar' }, { code: '08', name: 'Jhajjar' },
    { code: '09', name: 'Jind' }, { code: '10', name: 'Kaithal' },
    { code: '11', name: 'Karnal' }, { code: '12', name: 'Kurukshetra' },
    { code: '13', name: 'Mahendragarh' }, { code: '14', name: 'Nuh' },
    { code: '15', name: 'Palwal' }, { code: '16', name: 'Panchkula' },
    { code: '17', name: 'Panipat' }, { code: '18', name: 'Rewari' },
    { code: '19', name: 'Rohtak' }, { code: '20', name: 'Sirsa' },
    { code: '21', name: 'Sonipat' }, { code: '22', name: 'Yamunanagar' },
  ],
  '21': [ // Punjab
    { code: '01', name: 'Amritsar' }, { code: '02', name: 'Barnala' },
    { code: '03', name: 'Bathinda' }, { code: '04', name: 'Faridkot' },
    { code: '05', name: 'Fatehgarh Sahib' }, { code: '06', name: 'Fazilka' },
    { code: '07', name: 'Ferozepur' }, { code: '08', name: 'Gurdaspur' },
    { code: '09', name: 'Hoshiarpur' }, { code: '10', name: 'Jalandhar' },
    { code: '11', name: 'Kapurthala' }, { code: '12', name: 'Ludhiana' },
    { code: '13', name: 'Malerkotla' }, { code: '14', name: 'Mansa' },
    { code: '15', name: 'Moga' }, { code: '16', name: 'Mohali (SAS Nagar)' },
    { code: '17', name: 'Muktsar' }, { code: '18', name: 'Nawanshahr' },
    { code: '19', name: 'Pathankot' }, { code: '20', name: 'Patiala' },
    { code: '21', name: 'Rupnagar' }, { code: '22', name: 'Sangrur' },
    { code: '23', name: 'Tarn Taran' },
  ],
  '14': [ // Madhya Pradesh
    { code: '01', name: 'Bhopal' }, { code: '02', name: 'Indore' },
    { code: '03', name: 'Jabalpur' }, { code: '04', name: 'Gwalior' },
    { code: '05', name: 'Rewa' }, { code: '06', name: 'Sagar' },
    { code: '07', name: 'Ujjain' }, { code: '08', name: 'Satna' },
    { code: '09', name: 'Morena' }, { code: '10', name: 'Bhind' },
    { code: '11', name: 'Shivpuri' }, { code: '12', name: 'Guna' },
    { code: '13', name: 'Datia' }, { code: '14', name: 'Vidisha' },
    { code: '15', name: 'Raisen' }, { code: '16', name: 'Sehore' },
    { code: '17', name: 'Hoshangabad (Narmadapuram)' }, { code: '18', name: 'Betul' },
    { code: '19', name: 'Chhindwara' }, { code: '20', name: 'Seoni' },
    { code: '21', name: 'Narsinghpur' }, { code: '22', name: 'Mandla' },
    { code: '23', name: 'Dindori' }, { code: '24', name: 'Balaghat' },
    { code: '25', name: 'Katni' }, { code: '26', name: 'Umaria' },
    { code: '27', name: 'Shahdol' }, { code: '28', name: 'Anuppur' },
    { code: '29', name: 'Panna' }, { code: '30', name: 'Chhatarpur' },
    { code: '31', name: 'Tikamgarh' }, { code: '32', name: 'Damoh' },
    { code: '33', name: 'Sidhi' }, { code: '34', name: 'Singrauli' },
    { code: '35', name: 'Ratlam' }, { code: '36', name: 'Mandsaur' },
    { code: '37', name: 'Neemuch' }, { code: '38', name: 'Dewas' },
    { code: '39', name: 'Shajapur' }, { code: '40', name: 'Agar Malwa' },
    { code: '41', name: 'Rajgarh' }, { code: '42', name: 'Dhar' },
    { code: '43', name: 'Alirajpur' }, { code: '44', name: 'Jhabua' },
    { code: '45', name: 'Barwani' }, { code: '46', name: 'Khargone' },
    { code: '47', name: 'Burhanpur' }, { code: '48', name: 'Khandwa' },
    { code: '49', name: 'Harda' },
  ],
  '4': [ // Bihar
    { code: '01', name: 'Patna' }, { code: '02', name: 'Gaya' },
    { code: '03', name: 'Bhojpur' }, { code: '04', name: 'Rohtas' },
    { code: '05', name: 'Kaimur' }, { code: '06', name: 'Buxar' },
    { code: '07', name: 'Nalanda' }, { code: '08', name: 'Jehanabad' },
    { code: '09', name: 'Arwal' }, { code: '10', name: 'Aurangabad' },
    { code: '11', name: 'Nawada' }, { code: '12', name: 'Sheikhpura' },
    { code: '13', name: 'Lakhisarai' }, { code: '14', name: 'Begusarai' },
    { code: '15', name: 'Munger' }, { code: '16', name: 'Jamui' },
    { code: '17', name: 'Khagaria' }, { code: '18', name: 'Saharsa' },
    { code: '19', name: 'Supaul' }, { code: '20', name: 'Madhepura' },
    { code: '21', name: 'Bhagalpur' }, { code: '22', name: 'Banka' },
    { code: '23', name: 'Darbhanga' }, { code: '24', name: 'Madhubani' },
    { code: '25', name: 'Sitamarhi' }, { code: '26', name: 'Sheohar' },
    { code: '27', name: 'Muzaffarpur' }, { code: '28', name: 'West Champaran' },
    { code: '29', name: 'East Champaran' }, { code: '30', name: 'Gopalganj' },
    { code: '31', name: 'Siwan' }, { code: '32', name: 'Saran' },
    { code: '33', name: 'Vaishali' }, { code: '34', name: 'Samastipur' },
    { code: '35', name: 'Purnia' }, { code: '36', name: 'Kishanganj' },
    { code: '37', name: 'Araria' }, { code: '38', name: 'Katihar' },
  ],
  '20': [ // Odisha
    { code: '01', name: 'Khordha' }, { code: '02', name: 'Cuttack' },
    { code: '03', name: 'Puri' }, { code: '04', name: 'Nayagarh' },
    { code: '05', name: 'Kendrapara' }, { code: '06', name: 'Jagatsinghpur' },
    { code: '07', name: 'Jajpur' }, { code: '08', name: 'Bhadrak' },
    { code: '09', name: 'Balasore' }, { code: '10', name: 'Mayurbhanj' },
    { code: '11', name: 'Sundargarh' }, { code: '12', name: 'Jharsuguda' },
    { code: '13', name: 'Sambalpur' }, { code: '14', name: 'Bargarh' },
    { code: '15', name: 'Balangir' }, { code: '16', name: 'Subarnapur' },
    { code: '17', name: 'Nuapada' }, { code: '18', name: 'Kalahandi' },
    { code: '19', name: 'Kandhamal' }, { code: '20', name: 'Ganjam' },
    { code: '21', name: 'Gajapati' }, { code: '22', name: 'Rayagada' },
    { code: '23', name: 'Koraput' }, { code: '24', name: 'Malkangiri' },
    { code: '25', name: 'Nabarangpur' }, { code: '26', name: 'Keonjhar' },
    { code: '27', name: 'Dhenkanal' }, { code: '28', name: 'Angul' },
    { code: '29', name: 'Deogarh' }, { code: '30', name: 'Boudh' },
  ],
  '3': [ { code: '01', name: 'Baksa' }, { code: '02', name: 'Barpeta' }, { code: '03', name: 'Biswanath' }, { code: '04', name: 'Bongaigaon' }, { code: '05', name: 'Cachar' }, { code: '06', name: 'Charaideo' }, { code: '07', name: 'Chirang' }, { code: '08', name: 'Darrang' }, { code: '09', name: 'Dhemaji' }, { code: '10', name: 'Dhubri' }, { code: '11', name: 'Dibrugarh' }, { code: '12', name: 'Dima Hasao' }, { code: '13', name: 'Goalpara' }, { code: '14', name: 'Golaghat' }, { code: '15', name: 'Hailakandi' }, { code: '16', name: 'Hojai' }, { code: '17', name: 'Jorhat' }, { code: '18', name: 'Kamrup' }, { code: '19', name: 'Kamrup Metropolitan' }, { code: '20', name: 'Karbi Anglong' }, { code: '21', name: 'Karimganj' }, { code: '22', name: 'Kokrajhar' }, { code: '23', name: 'Lakhimpur' }, { code: '24', name: 'Majuli' }, { code: '25', name: 'Morigaon' }, { code: '26', name: 'Nagaon' }, { code: '27', name: 'Nalbari' }, { code: '28', name: 'Sivasagar' }, { code: '29', name: 'Sonitpur' }, { code: '30', name: 'South Salmara Mankachar' }, { code: '31', name: 'Tinsukia' }, { code: '32', name: 'Udalguri' }, { code: '33', name: 'West Karbi Anglong' } ],
  '9':  [ { code: '01', name: 'Bilaspur' }, { code: '02', name: 'Chamba' }, { code: '03', name: 'Hamirpur' }, { code: '04', name: 'Kangra' }, { code: '05', name: 'Kinnaur' }, { code: '06', name: 'Kullu' }, { code: '07', name: 'Lahaul and Spiti' }, { code: '08', name: 'Mandi' }, { code: '09', name: 'Shimla' }, { code: '10', name: 'Sirmaur' }, { code: '11', name: 'Solan' }, { code: '12', name: 'Una' } ],
  '10': [ { code: '01', name: 'Jammu' }, { code: '02', name: 'Samba' }, { code: '03', name: 'Kathua' }, { code: '04', name: 'Udhampur' }, { code: '05', name: 'Reasi' }, { code: '06', name: 'Doda' }, { code: '07', name: 'Ramban' }, { code: '08', name: 'Kishtwar' }, { code: '09', name: 'Poonch' }, { code: '10', name: 'Rajouri' }, { code: '11', name: 'Srinagar' }, { code: '12', name: 'Budgam' }, { code: '13', name: 'Pulwama' }, { code: '14', name: 'Shopian' }, { code: '15', name: 'Kulgam' }, { code: '16', name: 'Anantnag' }, { code: '17', name: 'Kargil' }, { code: '18', name: 'Baramulla' }, { code: '19', name: 'Kupwara' }, { code: '20', name: 'Bandipora' }, { code: '21', name: 'Ganderbal' } ],
  '11': [ { code: '01', name: 'Ranchi' }, { code: '02', name: 'Bokaro' }, { code: '03', name: 'Dhanbad' }, { code: '04', name: 'Giridih' }, { code: '05', name: 'Hazaribagh' }, { code: '06', name: 'Koderma' }, { code: '07', name: 'Ramgarh' }, { code: '08', name: 'Chatra' }, { code: '09', name: 'Latehar' }, { code: '10', name: 'Palamu' }, { code: '11', name: 'Garwha' }, { code: '12', name: 'Dumka' }, { code: '13', name: 'Jamtara' }, { code: '14', name: 'Deoghar' }, { code: '15', name: 'Godda' }, { code: '16', name: 'Sahibganj' }, { code: '17', name: 'Pakur' }, { code: '18', name: 'East Singhbhum' }, { code: '19', name: 'Seraikela-Kharsawan' }, { code: '20', name: 'West Singhbhum' }, { code: '21', name: 'Simdega' }, { code: '22', name: 'Gumla' }, { code: '23', name: 'Khunti' }, { code: '24', name: 'Lohardaga' } ],
  '5':  [ { code: '01', name: 'Raipur' }, { code: '02', name: 'Durg' }, { code: '03', name: 'Bilaspur' }, { code: '04', name: 'Raigarh' }, { code: '05', name: 'Jashpur' }, { code: '06', name: 'Korba' }, { code: '07', name: 'Janjgir-Champa' }, { code: '08', name: 'Koriya' }, { code: '09', name: 'Surguja' }, { code: '10', name: 'Surajpur' }, { code: '11', name: 'Balrampur' }, { code: '12', name: 'Narayanpur' }, { code: '13', name: 'Bijapur' }, { code: '14', name: 'Dantewada' }, { code: '15', name: 'Bastar' }, { code: '16', name: 'Kondagaon' }, { code: '17', name: 'Kanker' }, { code: '18', name: 'Balod' }, { code: '19', name: 'Gariaband' }, { code: '20', name: 'Mahasamund' }, { code: '21', name: 'Dhamtari' }, { code: '22', name: 'Bemetara' }, { code: '23', name: 'Mungeli' }, { code: '24', name: 'Rajnandgaon' }, { code: '25', name: 'Mohla-Manpur' }, { code: '26', name: 'Kabirdham' }, { code: '27', name: 'Gaurela-Pendra-Marwahi' }, { code: '28', name: 'Sakti' }, { code: '29', name: 'Manendragarh' } ],
  '6':  [ { code: '01', name: 'North Goa' }, { code: '02', name: 'South Goa' } ],
  '28': [ { code: '01', name: 'Dehradun' }, { code: '02', name: 'Haridwar' }, { code: '03', name: 'Pauri Garhwal' }, { code: '04', name: 'Tehri Garhwal' }, { code: '05', name: 'Uttarkashi' }, { code: '06', name: 'Rudraprayag' }, { code: '07', name: 'Chamoli' }, { code: '08', name: 'Pithoragarh' }, { code: '09', name: 'Bageshwar' }, { code: '10', name: 'Almora' }, { code: '11', name: 'Champawat' }, { code: '12', name: 'Nainital' }, { code: '13', name: 'Udham Singh Nagar' } ],
  '31': [ { code: '01', name: 'Chandigarh' } ],
  '30': [ { code: '01', name: 'South Andaman' }, { code: '02', name: 'North and Middle Andaman' }, { code: '03', name: 'Nicobar' } ],
  '2':  [ { code: '01', name: 'Anjaw' }, { code: '02', name: 'Changlang' }, { code: '03', name: 'East Kameng' }, { code: '04', name: 'East Siang' }, { code: '05', name: 'Kra Daadi' }, { code: '06', name: 'Kurung Kumey' }, { code: '07', name: 'Lohit' }, { code: '08', name: 'Longding' }, { code: '09', name: 'Lower Dibang Valley' }, { code: '10', name: 'Lower Siang' }, { code: '11', name: 'Lower Subansiri' }, { code: '12', name: 'Namsai' }, { code: '13', name: 'Papum Pare' }, { code: '14', name: 'Shi Yomi' }, { code: '15', name: 'Siang' }, { code: '16', name: 'Tawang' }, { code: '17', name: 'Tirap' }, { code: '18', name: 'Upper Dibang Valley' }, { code: '19', name: 'Upper Siang' }, { code: '20', name: 'Upper Subansiri' }, { code: '21', name: 'West Kameng' }, { code: '22', name: 'West Siang' } ],
  '16': [ { code: '01', name: 'Bishnupur' }, { code: '02', name: 'Chandel' }, { code: '03', name: 'Churachandpur' }, { code: '04', name: 'Imphal East' }, { code: '05', name: 'Imphal West' }, { code: '06', name: 'Jiribam' }, { code: '07', name: 'Kakching' }, { code: '08', name: 'Kamjong' }, { code: '09', name: 'Kangpokpi' }, { code: '10', name: 'Noney' }, { code: '11', name: 'Pherzawl' }, { code: '12', name: 'Senapati' }, { code: '13', name: 'Tamenglong' }, { code: '14', name: 'Tengnoupal' }, { code: '15', name: 'Thoubal' }, { code: '16', name: 'Ukhrul' } ],
  '17': [ { code: '01', name: 'East Garo Hills' }, { code: '02', name: 'East Jaintia Hills' }, { code: '03', name: 'East Khasi Hills' }, { code: '04', name: 'North Garo Hills' }, { code: '05', name: 'Ri Bhoi' }, { code: '06', name: 'South Garo Hills' }, { code: '07', name: 'South West Garo Hills' }, { code: '08', name: 'South West Khasi Hills' }, { code: '09', name: 'West Garo Hills' }, { code: '10', name: 'West Jaintia Hills' }, { code: '11', name: 'West Khasi Hills' } ],
  '18': [ { code: '01', name: 'Aizawl' }, { code: '02', name: 'Champhai' }, { code: '03', name: 'Hnahthial' }, { code: '04', name: 'Kolasib' }, { code: '05', name: 'Khawzawl' }, { code: '06', name: 'Lawngtlai' }, { code: '07', name: 'Lunglei' }, { code: '08', name: 'Mamit' }, { code: '09', name: 'Saiha' }, { code: '10', name: 'Saitual' }, { code: '11', name: 'Serchhip' } ],
  '19': [ { code: '01', name: 'Dimapur' }, { code: '02', name: 'Kiphire' }, { code: '03', name: 'Kohima' }, { code: '04', name: 'Longleng' }, { code: '05', name: 'Mokokchung' }, { code: '06', name: 'Mon' }, { code: '07', name: 'Noklak' }, { code: '08', name: 'Peren' }, { code: '09', name: 'Phek' }, { code: '10', name: 'Tuensang' }, { code: '11', name: 'Wokha' }, { code: '12', name: 'Zunheboto' } ],
  '36': [ { code: '01', name: 'Karaikal' }, { code: '02', name: 'Mahe' }, { code: '03', name: 'Puducherry' }, { code: '04', name: 'Yanam' } ],
  '23': [ { code: '01', name: 'East District' }, { code: '02', name: 'North Sikkim' }, { code: '03', name: 'South Sikkim' }, { code: '04', name: 'West Sikkim' } ],
  '26': [ { code: '01', name: 'Dhalai' }, { code: '02', name: 'Gomati' }, { code: '03', name: 'Khowai' }, { code: '04', name: 'North Tripura' }, { code: '05', name: 'Sepahijala' }, { code: '06', name: 'South Tripura' }, { code: '07', name: 'Unakoti' }, { code: '08', name: 'West Tripura' } ],
  '32': [ { code: '01', name: 'Dadra & Nagar Haveli' }, { code: '02', name: 'Daman' }, { code: '03', name: 'Diu' } ],
  '34': [ { code: '01', name: 'Leh' }, { code: '02', name: 'Kargil' } ],
  '35': [ { code: '01', name: 'Lakshadweep' } ],
};

// ── Court Complexes (keyed by "stateCode_distCode") ───────────────────────────
// For most districts we default to "All courts in district".
// Major cities have real complex entries.
const _def = (distName: string): Complex[] => [{ code: 'ALL', name: `All courts in ${distName}` }];

export const COURT_COMPLEXES: Record<string, Complex[]> = {
  // Delhi
  '33_01': [{ code: 'DLCCD001', name: 'Tis Hazari Court Complex' }, { code: 'DLCCD002', name: 'Patiala House Courts' }],
  '33_03': [{ code: 'DLNDC001', name: 'Saket District Courts' }, { code: 'DLNDC002', name: 'New Delhi Courts (PHC)' }],
  '33_08': [{ code: 'DLSCD001', name: 'Saket Courts Complex' }, { code: 'DLSCD002', name: 'Karkardooma Courts' }],
  '33_04': [{ code: 'DLNDD001', name: 'Rohini Courts Complex' }],
  '33_05': [{ code: 'DLNED001', name: 'Karkardooma Courts' }],
  // Mumbai / Maharashtra
  '15_01': [{ code: 'MHMCC001', name: 'City Civil & Sessions Court Mumbai' }, { code: 'MHMCC002', name: 'Esplanade Court Complex' }, { code: 'MHMCC003', name: 'Mazgaon Court Complex' }],
  '15_02': [{ code: 'MHMSC001', name: 'Dindoshi Court Complex' }, { code: 'MHMSC002', name: 'Borivali Court Complex' }, { code: 'MHMSC003', name: 'Bandra Court Complex' }],
  '15_03': [{ code: 'MHTHC001', name: 'Thane District Court' }, { code: 'MHTHC002', name: 'Kalyan Court Complex' }],
  '15_04': [{ code: 'MHPNC001', name: 'Pune District Court' }, { code: 'MHPNC002', name: 'Shivajinagar Court Complex' }],
  '15_07': [{ code: 'MHNGC001', name: 'Nagpur District & Sessions Court' }],
  // Bangalore / Karnataka
  '12_01': [{ code: 'KABNG001', name: 'City Civil & Sessions Court Bangalore' }, { code: 'KABNG002', name: 'Commercial Court Bangalore' }, { code: 'KABNG003', name: 'Family Court Bangalore' }],
  '12_03': [{ code: 'KAMYS001', name: 'Mysuru Principal District Court' }],
  // Chennai / Tamil Nadu
  '24_01': [{ code: 'TNCHN001', name: 'City Civil Court Chennai' }, { code: 'TNCHN002', name: 'Egmore Courts Complex' }, { code: 'TNCHN003', name: 'George Town Court Complex' }],
  '24_23': [{ code: 'TNMDU001', name: 'Madurai District Court' }],
  '24_14': [{ code: 'TNTRC001', name: 'Tiruchirappalli District Court' }],
  // Hyderabad / Telangana
  '25_01': [{ code: 'TGHYD001', name: 'City Civil Court Hyderabad' }, { code: 'TGHYD002', name: 'Nampally Court Complex' }],
  '25_02': [{ code: 'TGRRD001', name: 'Ranga Reddy District Court' }],
  // Lucknow / Uttar Pradesh
  '27_49': [{ code: 'UPLKO001', name: 'Lucknow District & Sessions Court' }],
  '27_43': [{ code: 'UPKPR001', name: 'Kanpur Nagar District Court' }],
  '27_03': [{ code: 'UPILH001', name: 'Prayagraj District Court' }],
  '27_55': [{ code: 'UPMRT001', name: 'Meerut District Court' }],
  // Ahmedabad / Gujarat
  '7_01':  [{ code: 'GJAMD001', name: 'City Civil & Sessions Court Ahmedabad' }, { code: 'GJAMD002', name: 'Commercial Court Ahmedabad' }],
  '7_27':  [{ code: 'GJRJK001', name: 'Rajkot District Court' }],
  '7_29':  [{ code: 'GJSRT001', name: 'Surat District Court' }],
  // Jaipur / Rajasthan
  '22_16': [{ code: 'RJJPR001', name: 'Jaipur District Court' }, { code: 'RJJPR002', name: 'Jaipur Metropolitan Magistrate' }],
  '22_21': [{ code: 'RJJDH001', name: 'Jodhpur District Court' }],
  '22_23': [{ code: 'RJKOT001', name: 'Kota District Court' }],
  // Kolkata / West Bengal
  '29_01': [{ code: 'WBKOL001', name: 'City Civil Court Kolkata' }, { code: 'WBKOL002', name: 'Calcutta High Court Original Side' }],
  '29_02': [{ code: 'WBHWH001', name: 'Howrah District Court' }],
  // Patna / Bihar
  '4_01':  [{ code: 'BRPTN001', name: 'Patna District Court' }],
  // Bhopal / MP
  '14_01': [{ code: 'MPBPL001', name: 'Bhopal District Court' }],
  '14_02': [{ code: 'MPIND001', name: 'Indore District Court' }],
  // Chandigarh
  '31_01': [{ code: 'CHCHD001', name: 'Chandigarh District Courts' }],
};

/** Returns complexes for a given (stateCode, distCode) pair */
export function getComplexes(stateCode: string, distCode: string): Complex[] {
  const key = `${stateCode}_${distCode}`;
  return COURT_COMPLEXES[key] ?? [];
}

/** Returns districts for a given state code */
export function getDistricts(stateCode: string): District[] {
  return DISTRICTS[stateCode] ?? [];
}

// ── CNR State Code Map ────────────────────────────────────────────────────────
export const CNR_STATE_CODES: Record<string, string> = {
  AP: 'Andhra Pradesh',  AR: 'Arunachal Pradesh', AS: 'Assam',
  BR: 'Bihar',           CH: 'Chandigarh',         CG: 'Chhattisgarh',
  DD: 'Dadra & NH / Daman & Diu', DL: 'Delhi',    GA: 'Goa',
  GJ: 'Gujarat',         HR: 'Haryana',            HP: 'Himachal Pradesh',
  JK: 'Jammu & Kashmir', JH: 'Jharkhand',           KA: 'Karnataka',
  KL: 'Kerala',          LA: 'Ladakh',             LD: 'Lakshadweep',
  MP: 'Madhya Pradesh',  MH: 'Maharashtra',         MN: 'Manipur',
  ML: 'Meghalaya',       MZ: 'Mizoram',            NL: 'Nagaland',
  OR: 'Odisha',          PY: 'Puducherry',          PB: 'Punjab',
  RJ: 'Rajasthan',       SK: 'Sikkim',             TN: 'Tamil Nadu',
  TG: 'Telangana',       TR: 'Tripura',            UP: 'Uttar Pradesh',
  UK: 'Uttarakhand',     WB: 'West Bengal',        AN: 'Andaman & Nicobar',
};

// ── CNR Court Type Code Map ───────────────────────────────────────────────────
export const CNR_COURT_CODES: Record<string, string> = {
  HC: 'High Court',
  DC: 'District Court',
  JD: 'Judicial District Court',
  CC: 'City Civil Court',
  SC: 'Sessions Court',
  FC: 'Family Court',
  MM: "Metropolitan Magistrate's Court",
  MC: "Magistrate's Court",
  CJ: 'Chief Judicial Magistrate',
  JM: 'Judicial Magistrate',
  CM: 'Civil & Sessions Court',
  RC: 'Revenue Court',
  LC: 'Labour Court',
  AC: 'Administrative Court',
  TC: 'Tribunal Court',
};

export const CASE_TYPES = [
  { code: '',    name: 'All case types' },
  { code: '1',   name: 'Criminal' },
  { code: '2',   name: 'Civil' },
  { code: '3',   name: 'Family / Matrimonial' },
  { code: '4',   name: 'Motor Accident' },
  { code: '5',   name: 'Consumer' },
  { code: '6',   name: 'Labour' },
  { code: '7',   name: 'Revenue' },
  { code: '8',   name: 'Writ / Constitutional' },
];

export const STATE_BAR_COUNCILS = [
  'Bar Council of Andhra Pradesh',
  'Bar Council of Assam, Nagaland, Meghalaya, Manipur, Tripura, Mizoram & Arunachal Pradesh',
  'Bar Council of Bihar',
  'Bar Council of Chhattisgarh',
  'Bar Council of Delhi',
  'Bar Council of Gujarat',
  'Bar Council of Himachal Pradesh',
  'Bar Council of Jammu & Kashmir & Ladakh',
  'Bar Council of Jharkhand',
  'Bar Council of Karnataka',
  'Bar Council of Kerala',
  'Bar Council of Madhya Pradesh',
  'Bar Council of Maharashtra & Goa',
  'Bar Council of Odisha',
  'Bar Council of Punjab & Haryana',
  'Bar Council of Rajasthan',
  'Bar Council of Sikkim',
  'Bar Council of Tamil Nadu & Puducherry',
  'Bar Council of Telangana',
  'Bar Council of Uttar Pradesh',
  'Bar Council of Uttarakhand',
  'Bar Council of West Bengal',
];
