export const STATES_UTS: { code: string; name: string }[] = [
  { code: "1",  name: "Andhra Pradesh" },
  { code: "2",  name: "Arunachal Pradesh" },
  { code: "3",  name: "Assam" },
  { code: "4",  name: "Bihar" },
  { code: "5",  name: "Chhattisgarh" },
  { code: "6",  name: "Goa" },
  { code: "7",  name: "Gujarat" },
  { code: "8",  name: "Haryana" },
  { code: "9",  name: "Himachal Pradesh" },
  { code: "10", name: "Jharkhand" },
  { code: "11", name: "Karnataka" },
  { code: "12", name: "Kerala" },
  { code: "13", name: "Madhya Pradesh" },
  { code: "14", name: "Maharashtra" },
  { code: "15", name: "Manipur" },
  { code: "16", name: "Meghalaya" },
  { code: "17", name: "Mizoram" },
  { code: "18", name: "Nagaland" },
  { code: "19", name: "Odisha" },
  { code: "20", name: "Punjab" },
  { code: "21", name: "Rajasthan" },
  { code: "22", name: "Sikkim" },
  { code: "23", name: "Tamil Nadu" },
  { code: "24", name: "Telangana" },
  { code: "25", name: "Tripura" },
  { code: "26", name: "Uttar Pradesh" },
  { code: "27", name: "Uttarakhand" },
  { code: "28", name: "West Bengal" },
  { code: "29", name: "Andaman & Nicobar Islands" },
  { code: "30", name: "Chandigarh" },
  { code: "31", name: "Dadra & Nagar Haveli and Daman & Diu" },
  { code: "32", name: "Delhi" },
  { code: "33", name: "Jammu & Kashmir" },
  { code: "34", name: "Ladakh" },
  { code: "35", name: "Lakshadweep" },
  { code: "36", name: "Puducherry" },
];

export const DISTRICTS: { [stateCode: string]: { code: string; name: string }[] } = {
  "14": [
    { code: "1",  name: "Ahmednagar" },   { code: "2",  name: "Akola" },
    { code: "3",  name: "Amravati" },     { code: "4",  name: "Aurangabad" },
    { code: "5",  name: "Beed" },         { code: "6",  name: "Bhandara" },
    { code: "7",  name: "Buldhana" },     { code: "8",  name: "Chandrapur" },
    { code: "9",  name: "Dhule" },        { code: "10", name: "Gadchiroli" },
    { code: "11", name: "Gondia" },       { code: "12", name: "Hingoli" },
    { code: "13", name: "Jalgaon" },      { code: "14", name: "Jalna" },
    { code: "15", name: "Kolhapur" },     { code: "16", name: "Latur" },
    { code: "17", name: "Mumbai City" },  { code: "18", name: "Mumbai Suburban" },
    { code: "19", name: "Nagpur" },       { code: "20", name: "Nanded" },
    { code: "21", name: "Nandurbar" },    { code: "22", name: "Nashik" },
    { code: "23", name: "Osmanabad" },    { code: "24", name: "Palghar" },
    { code: "25", name: "Parbhani" },     { code: "26", name: "Pune" },
    { code: "27", name: "Raigad" },       { code: "28", name: "Ratnagiri" },
    { code: "29", name: "Sangli" },       { code: "30", name: "Satara" },
    { code: "31", name: "Sindhudurg" },   { code: "32", name: "Solapur" },
    { code: "33", name: "Thane" },        { code: "34", name: "Wardha" },
    { code: "35", name: "Washim" },       { code: "36", name: "Yavatmal" },
  ],
  "32": [
    { code: "1",  name: "Central Delhi" },     { code: "2",  name: "East Delhi" },
    { code: "3",  name: "New Delhi" },         { code: "4",  name: "North Delhi" },
    { code: "5",  name: "North East Delhi" },  { code: "6",  name: "North West Delhi" },
    { code: "7",  name: "Shahdara" },          { code: "8",  name: "South Delhi" },
    { code: "9",  name: "South East Delhi" },  { code: "10", name: "South West Delhi" },
    { code: "11", name: "West Delhi" },
  ],
  "11": [
    { code: "1",  name: "Bagalkot" },       { code: "2",  name: "Ballari" },
    { code: "3",  name: "Belagavi" },       { code: "4",  name: "Bengaluru Rural" },
    { code: "5",  name: "Bengaluru Urban" },{ code: "6",  name: "Bidar" },
    { code: "7",  name: "Chamarajanagara" },{ code: "8",  name: "Chikkaballapura" },
    { code: "9",  name: "Chikkamagaluru" }, { code: "10", name: "Chitradurga" },
    { code: "11", name: "Dakshina Kannada" },{ code: "12", name: "Davanagere" },
    { code: "13", name: "Dharwad" },        { code: "14", name: "Gadag" },
    { code: "15", name: "Hassan" },         { code: "16", name: "Haveri" },
    { code: "17", name: "Kalaburagi" },     { code: "18", name: "Kodagu" },
    { code: "19", name: "Kolar" },          { code: "20", name: "Koppal" },
    { code: "21", name: "Mandya" },         { code: "22", name: "Mysuru" },
    { code: "23", name: "Raichur" },        { code: "24", name: "Ramanagara" },
    { code: "25", name: "Shivamogga" },     { code: "26", name: "Tumakuru" },
    { code: "27", name: "Udupi" },          { code: "28", name: "Uttara Kannada" },
    { code: "29", name: "Vijayapura" },     { code: "30", name: "Yadgir" },
  ],
  "23": [
    { code: "1",  name: "Ariyalur" },       { code: "2",  name: "Chengalpattu" },
    { code: "3",  name: "Chennai" },         { code: "4",  name: "Coimbatore" },
    { code: "5",  name: "Cuddalore" },       { code: "6",  name: "Dharmapuri" },
    { code: "7",  name: "Dindigul" },        { code: "8",  name: "Erode" },
    { code: "9",  name: "Kallakurichi" },    { code: "10", name: "Kancheepuram" },
    { code: "11", name: "Kanyakumari" },     { code: "12", name: "Karur" },
    { code: "13", name: "Krishnagiri" },     { code: "14", name: "Madurai" },
    { code: "15", name: "Mayiladuthurai" },  { code: "16", name: "Nagapattinam" },
    { code: "17", name: "Namakkal" },        { code: "18", name: "Nilgiris" },
    { code: "19", name: "Perambalur" },      { code: "20", name: "Pudukkottai" },
    { code: "21", name: "Ramanathapuram" },  { code: "22", name: "Ranipet" },
    { code: "23", name: "Salem" },           { code: "24", name: "Sivaganga" },
    { code: "25", name: "Tenkasi" },         { code: "26", name: "Thanjavur" },
    { code: "27", name: "Theni" },           { code: "28", name: "Thoothukudi" },
    { code: "29", name: "Tiruchirappalli" }, { code: "30", name: "Tirunelveli" },
    { code: "31", name: "Tirupathur" },      { code: "32", name: "Tiruppur" },
    { code: "33", name: "Tiruvallur" },      { code: "34", name: "Tiruvannamalai" },
    { code: "35", name: "Tiruvarur" },       { code: "36", name: "Vellore" },
    { code: "37", name: "Villupuram" },      { code: "38", name: "Virudhunagar" },
  ],
  "7": [
    { code: "1",  name: "Ahmedabad" },    { code: "2",  name: "Amreli" },
    { code: "3",  name: "Anand" },        { code: "4",  name: "Aravalli" },
    { code: "5",  name: "Banaskantha" },  { code: "6",  name: "Bharuch" },
    { code: "7",  name: "Bhavnagar" },    { code: "8",  name: "Botad" },
    { code: "9",  name: "Chhota Udaipur" },{ code: "10", name: "Dahod" },
    { code: "11", name: "Dang" },         { code: "12", name: "Devbhoomi Dwarka" },
    { code: "13", name: "Gandhinagar" },  { code: "14", name: "Gir Somnath" },
    { code: "15", name: "Jamnagar" },     { code: "16", name: "Junagadh" },
    { code: "17", name: "Kheda" },        { code: "18", name: "Kutch" },
    { code: "19", name: "Mahisagar" },    { code: "20", name: "Mehsana" },
    { code: "21", name: "Morbi" },        { code: "22", name: "Narmada" },
    { code: "23", name: "Navsari" },      { code: "24", name: "Panchmahal" },
    { code: "25", name: "Patan" },        { code: "26", name: "Porbandar" },
    { code: "27", name: "Rajkot" },       { code: "28", name: "Sabarkantha" },
    { code: "29", name: "Surat" },        { code: "30", name: "Surendranagar" },
    { code: "31", name: "Tapi" },         { code: "32", name: "Vadodara" },
    { code: "33", name: "Valsad" },
  ],
  "26": [
    { code: "1",  name: "Agra" },            { code: "2",  name: "Aligarh" },
    { code: "3",  name: "Ambedkar Nagar" },   { code: "4",  name: "Amethi" },
    { code: "5",  name: "Amroha" },           { code: "6",  name: "Auraiya" },
    { code: "7",  name: "Ayodhya" },          { code: "8",  name: "Azamgarh" },
    { code: "9",  name: "Baghpat" },          { code: "10", name: "Bahraich" },
    { code: "11", name: "Ballia" },           { code: "12", name: "Balrampur" },
    { code: "13", name: "Banda" },            { code: "14", name: "Barabanki" },
    { code: "15", name: "Bareilly" },         { code: "16", name: "Basti" },
    { code: "17", name: "Bijnor" },           { code: "18", name: "Budaun" },
    { code: "19", name: "Bulandshahr" },      { code: "20", name: "Chandauli" },
    { code: "21", name: "Chitrakoot" },       { code: "22", name: "Deoria" },
    { code: "23", name: "Etah" },             { code: "24", name: "Etawah" },
    { code: "25", name: "Farrukhabad" },      { code: "26", name: "Fatehpur" },
    { code: "27", name: "Firozabad" },        { code: "28", name: "Gautam Buddha Nagar" },
    { code: "29", name: "Ghaziabad" },        { code: "30", name: "Ghazipur" },
    { code: "31", name: "Gonda" },            { code: "32", name: "Gorakhpur" },
    { code: "33", name: "Hamirpur" },         { code: "34", name: "Hapur" },
    { code: "35", name: "Hardoi" },           { code: "36", name: "Hathras" },
    { code: "37", name: "Jalaun" },           { code: "38", name: "Jaunpur" },
    { code: "39", name: "Jhansi" },           { code: "40", name: "Kannauj" },
    { code: "41", name: "Kanpur Dehat" },     { code: "42", name: "Kanpur Nagar" },
    { code: "43", name: "Kasganj" },          { code: "44", name: "Kaushambi" },
    { code: "45", name: "Kushinagar" },       { code: "46", name: "Lakhimpur Kheri" },
    { code: "47", name: "Lalitpur" },         { code: "48", name: "Lucknow" },
    { code: "49", name: "Maharajganj" },      { code: "50", name: "Mahoba" },
    { code: "51", name: "Mainpuri" },         { code: "52", name: "Mathura" },
    { code: "53", name: "Mau" },              { code: "54", name: "Meerut" },
    { code: "55", name: "Mirzapur" },         { code: "56", name: "Moradabad" },
    { code: "57", name: "Muzaffarnagar" },    { code: "58", name: "Pilibhit" },
    { code: "59", name: "Pratapgarh" },       { code: "60", name: "Prayagraj" },
    { code: "61", name: "Raebareli" },        { code: "62", name: "Rampur" },
    { code: "63", name: "Saharanpur" },       { code: "64", name: "Sambhal" },
    { code: "65", name: "Sant Kabir Nagar" }, { code: "66", name: "Shahjahanpur" },
    { code: "67", name: "Shamli" },           { code: "68", name: "Shravasti" },
    { code: "69", name: "Siddharthnagar" },   { code: "70", name: "Sitapur" },
    { code: "71", name: "Sonbhadra" },        { code: "72", name: "Sultanpur" },
    { code: "73", name: "Unnao" },            { code: "74", name: "Varanasi" },
  ],
};

export const CNR_STATE_CODES: { [prefix: string]: string } = {
  AP: "Andhra Pradesh",   AR: "Arunachal Pradesh", AS: "Assam",
  BR: "Bihar",            CG: "Chhattisgarh",      CH: "Chandigarh",
  DD: "Dadra & NH / D&D", DL: "Delhi",             GA: "Goa",
  GJ: "Gujarat",          HR: "Haryana",           HP: "Himachal Pradesh",
  JK: "Jammu & Kashmir",  JH: "Jharkhand",         KA: "Karnataka",
  KL: "Kerala",           LA: "Ladakh",            LD: "Lakshadweep",
  MP: "Madhya Pradesh",   MH: "Maharashtra",       MN: "Manipur",
  ML: "Meghalaya",        MZ: "Mizoram",           NL: "Nagaland",
  OD: "Odisha",           PB: "Punjab",            PY: "Puducherry",
  RJ: "Rajasthan",        SK: "Sikkim",            TN: "Tamil Nadu",
  TG: "Telangana",        TR: "Tripura",           UP: "Uttar Pradesh",
  UK: "Uttarakhand",      WB: "West Bengal",       AN: "Andaman & Nicobar",
};

export const CNR_COURT_CODES: { [prefix: string]: string } = {
  HC: "High Court",          DC: "District Court",
  JD: "Judicial District",   CC: "City Civil Court",
  SC: "Sessions Court",      FC: "Family Court",
  MM: "Metropolitan Magistrate", MC: "Magistrate Court",
  CJ: "Chief Judicial Magistrate", JM: "Judicial Magistrate",
};

export const buildPartySearchUrl = (
  stateCode: string,
  districtCode: string,
  partyName: string,
  partyType: "petitioner" | "respondent"
): string => {
  const typeCode = partyType === "petitioner" ? "1" : "2";
  return `https://services.ecourts.gov.in/ecourtindia_v6/?p=casestatus/index&app_token=&state_code=${stateCode}&dist_code=${districtCode}&party_name=${encodeURIComponent(partyName)}&party_type=${typeCode}&ajax_req=true`;
};

export const buildCNRUrl = (cnr: string): string =>
  `https://services.ecourts.gov.in/ecourtindia_v6/?p=casestatus/getCNRDetails&cnr_number=${cnr.trim().toUpperCase()}&ajax_req=true`;

/** All State / UT Bar Councils recognised by the Bar Council of India */
export const STATE_BAR_COUNCILS: string[] = [
  'Bar Council of Andhra Pradesh',
  'Bar Council of Assam, Nagaland, Meghalaya, Manipur, Tripura, Mizoram & Arunachal Pradesh',
  'Bar Council of Bihar',
  'Bar Council of Bombay (Maharashtra, Goa, Dadra & NH, Daman & Diu)',
  'Bar Council of Calcutta (West Bengal & Andaman Nicobar)',
  'Bar Council of Chhattisgarh',
  'Bar Council of Delhi',
  'Bar Council of Gujarat',
  'Bar Council of Himachal Pradesh',
  'Bar Council of Jammu & Kashmir & Ladakh',
  'Bar Council of Jharkhand',
  'Bar Council of Karnataka',
  'Bar Council of Kerala',
  'Bar Council of Madhya Pradesh',
  'Bar Council of Odisha',
  'Bar Council of Punjab & Haryana',
  'Bar Council of Rajasthan',
  'Bar Council of Sikkim',
  'Bar Council of Tamil Nadu',
  'Bar Council of Telangana',
  'Bar Council of Uttar Pradesh',
  'Bar Council of Uttarakhand',
];
