export const theme = {
  colors: {
    surface: '#FDFBF7',
    onSurface: '#1A202C',
    surfaceSecondary: '#F4F1EA',
    onSurfaceSecondary: '#374151',
    surfaceTertiary: '#EAE4D9',
    onSurfaceTertiary: '#4B5563',
    surfaceInverse: '#1A202C',
    onSurfaceInverse: '#FDFBF7',
    // Royal Blue + Gold brand palette
    brand: '#12328C',
    brandPrimary: '#12328C',
    onBrandPrimary: '#FDFBF7',
    brandSecondary: '#9A6E00',
    onBrandSecondary: '#FFFFFF',
    brandTertiary: '#1B4BB8',
    onBrandTertiary: '#FDFBF7',
    gold: '#D4AF37',
    goldSoft: '#F5E3A3',
    success: '#2D6A4F',
    warning: '#D97706',
    error: '#B91C1C',
    info: '#1E40AF',
    border: '#D1D5DB',
    borderStrong: '#9CA3AF',
    divider: '#E5E7EB',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    xxxl: 48,
  },
  radius: {
    sm: 6,
    md: 12,
    lg: 20,
    pill: 999,
  },
  fonts: {
    // Native serif fallback family — dignified editorial feel
    display: 'serif',
    displayRegular: 'serif',
    body: 'System',
    bodyMedium: 'System',
    bodyBold: 'System',
  },
} as const;
