export const theme = {
  colors: {
    surface: '#FDFBF7',
    onSurface: '#1A202C',
    surfaceSecondary: '#F4F1EA',
    onSurfaceSecondary: '#374151',
    surfaceTertiary: '#EAE4D9',
    onSurfaceTertiary: '#4B5563',
    surfaceInverse: '#1A202C',
    onSurfaceInverse: '#FDFBF7',
    brand: '#0A1C3A',
    brandPrimary: '#0A1C3A',
    onBrandPrimary: '#FDFBF7',
    brandSecondary: '#C65D3B',
    onBrandSecondary: '#FDFBF7',
    brandTertiary: '#4B6F54',
    onBrandTertiary: '#FDFBF7',
    success: '#2D6A4F',
    warning: '#D97706',
    error: '#B91C1C',
    info: '#1E40AF',
    border: '#D1D5DB',
    borderStrong: '#9CA3AF',
    divider: '#E5E7EB',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    xxxl: 48,
  },
  radius: {
    sm: 6,
    md: 12,
    lg: 20,
    pill: 999,
  },
  fonts: {
    // Native serif fallback family — dignified editorial feel
    display: 'serif',
    displayRegular: 'serif',
    body: 'System',
    bodyMedium: 'System',
    bodyBold: 'System',
  },
} as const;
