/** Shared navy / white / gold palette. Dark gold is reserved for text on white. */
export const theme = {
  colors: {
    surface: '#FFFFFF',
    onSurface: '#111827',
    surfaceSecondary: '#F3F4F6',
    background: '#F3F3F8',
    onSurfaceSecondary: '#374151',
    surfaceTertiary: '#E8EBF0',
    onSurfaceTertiary: '#4B5563',
    surfaceInverse: '#0B1D3A',
    onSurfaceInverse: '#FFFFFF',
    brand: '#0B1D3A',
    brandPrimary: '#0B1D3A',
    onBrandPrimary: '#FFFFFF',
    brandSecondary: '#9A6E00',
    onBrandSecondary: '#FFFFFF',
    brandTertiary: '#152E59',
    onBrandTertiary: '#FFFFFF',
    gold: '#D4AF37',
    goldSoft: '#F5E3A3',
    goldMuted: '#FCF8E9',
    onGold: '#0B1D3A',
    onNavyMuted: '#DCE4F0',
    navySoft: '#EAF0F7',
    navyOverlay: 'rgba(255,255,255,0.10)',
    shadow: 'rgba(11,29,58,0.10)',
    accent: '#D4AF37',
    accentDark: '#B8972E',
    primary: '#0B1D3A',
    primaryMid: '#152E59',
    success: '#2D6A4F',
    successSoft: '#EDF8F2',
    warning: '#896A12',
    error: '#B91C1C',
    info: '#152E59',
    border: '#D1D5DB',
    borderStrong: '#9CA3AF',
    divider: '#E5E7EB',
  },
  // Compatibility aliases for existing auth, FIR, and legal document screens.
  dhara: {
    navy: '#0B1D3A',
    navyLight: '#152E59',
    gold: '#D4AF37',
    goldDark: '#896A12',
    cream: '#F3F4F6',
    textPrimary: '#0B1D3A',
    textSecondary: '#4A5A6E',
    textOnNavy: '#FFFFFF',
    textOnNavyMuted: '#DCE4F0',
  },
  spacing: { xs: 4, sm: 8, md: 12, lg: 16, xl: 24, xxl: 32, xxxl: 48 },
  radius: { sm: 6, md: 12, lg: 20, pill: 999 },
  fonts: {
    display: 'serif', displayRegular: 'serif', body: 'System', bodyMedium: 'System', bodyBold: 'System',
  },
} as const;